run:
  deadline: 10m
  skip-dirs:
    - temp
  skip-files:
    - ".*_gen.go$"
  tests: false
  sort-results: true
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gochecknoglobals
    - nlreturn
    - scopelint
    - maligned
    - interfacer
    - wrapcheck
    - golint
    - exhaustive
    - exhaustruct
    - nosnakecase
    - deadcode
    - varcheck
    - structcheck
    - ifshort
    - depguard
linters-settings:
  godox:
    keywords:
      - NOTE
      - HACK
      - TEMP
      - FIX
      - FIXME
  cyclop:
    max-complexity: 15
  varnamelen:
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-decls:
      - p Process
      - l zerolog.Logger
      - b []byte
    ignore-names:
      - ss
      - id
      - to
    max-distance: 10
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/gofoji/foji)