// Code generated by foji (dev build), template: foji/openapi/client.go.tpl; DO NOT EDIT.

package auth

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"

	"github.com/bir/iken/httputil"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/clientcredentials"
)

type Doer interface {
	Do(*http.Request) (*http.Response, error)
}

type ClientOption func(*Client)

type Client struct {
	baseURL                              string
	doer                                 Doer
	apiKeyCookieToken                    string
	apiKeyHeaderToken                    string
	apiKeyQueryToken                     string
	basicAuthUsername                    string
	basicAuthPassword                    string
	bearerAuthToken                      string
	oauth2ClientCredentialsExampleConfig *clientcredentials.Config
	oauth2ExampleConfig                  oauth2.Config
	openIdconnectConfig                  oauth2.Config
	rawToken                             string
}

func NewClient(baseURL string, doer Doer, opts ...ClientOption) *Client {
	c := &Client{baseURL: baseURL, doer: doer}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

func WithApiKeyCookieToken(token string) ClientOption {
	return func(c *Client) {
		c.apiKeyCookieToken = token
	}
}

func WithApiKeyHeaderToken(token string) ClientOption {
	return func(c *Client) {
		c.apiKeyHeaderToken = token
	}
}

func WithApiKeyQueryToken(token string) ClientOption {
	return func(c *Client) {
		c.apiKeyQueryToken = token
	}
}

func WithBasicAuthCredentials(username, password string) ClientOption {
	return func(c *Client) {
		c.basicAuthUsername = username
		c.basicAuthPassword = password
	}
}

func WithBearerAuthToken(token string) ClientOption {
	return func(c *Client) {
		c.bearerAuthToken = token
	}
}

func WithOauth2ClientCredentialsExampleConfig(config clientcredentials.Config) ClientOption {
	return func(c *Client) {
		c.oauth2ClientCredentialsExampleConfig = &config
	}
}

func WithOauth2ExampleConfig(config oauth2.Config) ClientOption {
	return func(c *Client) {
		c.oauth2ExampleConfig = config
	}
}

func WithOpenIdconnectConfig(config oauth2.Config) ClientOption {
	return func(c *Client) {
		c.openIdconnectConfig = config
	}
}

func WithRawToken(token string) ClientOption {
	return func(c *Client) {
		c.rawToken = token
	}
}

var ErrMissingAuthToken = errors.New("missing auth token")

type APIError struct {
	StatusCode int
	Status     string
	Body       []byte
}

func (e *APIError) Error() string {
	return fmt.Sprintf("%d %s: %s", e.StatusCode, e.Status, string(e.Body))
}

// ListAdminUsers
// List all users (admin only)
// Requires both API key AND bearer token with admin scope
func (c *Client) ListAdminUsers(ctx context.Context, apiKeyHeaderToken string, bearerAuthToken string) ([]User, error) {
	if apiKeyHeaderToken == "" {
		apiKeyHeaderToken = c.apiKeyHeaderToken
	}

	if bearerAuthToken == "" {
		bearerAuthToken = c.bearerAuthToken
	}

	if !(apiKeyHeaderToken != "" && bearerAuthToken != "") {
		return nil, ErrMissingAuthToken
	}

	u := c.baseURL + "/admin/users"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	if apiKeyHeaderToken != "" {
		req.Header.Set("X-API-Key", apiKeyHeaderToken)
	}

	if bearerAuthToken != "" {
		req.Header.Set("Authorization", "Bearer "+bearerAuthToken)
	}

	resp, err := c.doer.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	var out []User
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return out, nil
}

// QueryDataWithApiKey
// Query data with API key
// Accepts API key in header, query parameter, or cookie
func (c *Client) QueryDataWithApiKey(ctx context.Context, apiKeyCookieToken string, apiKeyHeaderToken string, apiKeyQueryToken string, rawToken string, query *string) error {
	if apiKeyCookieToken == "" {
		apiKeyCookieToken = c.apiKeyCookieToken
	}

	if apiKeyHeaderToken == "" {
		apiKeyHeaderToken = c.apiKeyHeaderToken
	}

	if apiKeyQueryToken == "" {
		apiKeyQueryToken = c.apiKeyQueryToken
	}

	if rawToken == "" {
		rawToken = c.rawToken
	}

	if !((apiKeyHeaderToken != "") || (apiKeyQueryToken != "") || (apiKeyCookieToken != "") || (rawToken != "")) {
		return ErrMissingAuthToken
	}

	u := c.baseURL + "/data/query"
	queryParams := url.Values{}
	if query != nil {
		queryParams.Set("query", (*query))
	}

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	if apiKeyCookieToken != "" {
		req.AddCookie(&http.Cookie{Name: "cookie_name", Value: apiKeyCookieToken})
	}

	if apiKeyHeaderToken != "" {
		req.Header.Set("X-API-Key", apiKeyHeaderToken)
	}

	if apiKeyQueryToken != "" {
		q := req.URL.Query()
		q.Set("query_key_name", apiKeyQueryToken)
		req.URL.RawQuery = q.Encode()
	}

	if rawToken != "" {
		req.Header.Set("Authorization", rawToken)
	}

	resp, err := c.doer.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	return nil
}

// ListDocuments
// List documents
// Requires basic authentication
func (c *Client) ListDocuments(ctx context.Context, basicAuthUsername string, basicAuthPassword string) error {
	if basicAuthUsername == "" {
		basicAuthUsername = c.basicAuthUsername
		basicAuthPassword = c.basicAuthPassword
	}

	if !(basicAuthUsername != "") {
		return ErrMissingAuthToken
	}

	u := c.baseURL + "/documents"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	if basicAuthUsername != "" {
		req.SetBasicAuth(basicAuthUsername, basicAuthPassword)
	}

	resp, err := c.doer.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	return nil
}

// CreateDocument
// Create document
// Requires API key with bearer token
func (c *Client) CreateDocument(ctx context.Context, apiKeyHeaderToken string, bearerAuthToken string) error {
	if apiKeyHeaderToken == "" {
		apiKeyHeaderToken = c.apiKeyHeaderToken
	}

	if bearerAuthToken == "" {
		bearerAuthToken = c.bearerAuthToken
	}

	if !(apiKeyHeaderToken != "" && bearerAuthToken != "") {
		return ErrMissingAuthToken
	}

	u := c.baseURL + "/documents"

	req, err := http.NewRequestWithContext(ctx, "POST", u, http.NoBody)
	if err != nil {
		return err
	}

	if apiKeyHeaderToken != "" {
		req.Header.Set("X-API-Key", apiKeyHeaderToken)
	}

	if bearerAuthToken != "" {
		req.Header.Set("Authorization", "Bearer "+bearerAuthToken)
	}

	resp, err := c.doer.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	return nil
}

// Overview
// System overview
// Requires OAuth client credentials
func (c *Client) Overview(ctx context.Context) error {
	if !(c.oauth2ClientCredentialsExampleConfig != nil) {
		return ErrMissingAuthToken
	}

	u := c.baseURL + "/overview"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}
	doer := c.doer

	if c.oauth2ClientCredentialsExampleConfig != nil {
		doer = c.oauth2ClientCredentialsExampleConfig.Client(context.WithValue(ctx, oauth2.HTTPClient, c.doer))
	}

	resp, err := doer.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	return nil
}

// GetDetailedProfile
// Get detailed profile
// Requires OpenID Connect authentication
func (c *Client) GetDetailedProfile(ctx context.Context, openIdconnectToken *oauth2.Token) error {
	if !(openIdconnectToken != nil) {
		return ErrMissingAuthToken
	}

	u := c.baseURL + "/profile/detailed"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}
	doer := c.doer

	if openIdconnectToken != nil {
		doer = c.openIdconnectConfig.Client(context.WithValue(ctx, oauth2.HTTPClient, c.doer), openIdconnectToken)
	}

	resp, err := doer.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	return nil
}

// GetProtectedResource
// Access protected resource
// Multiple authentication options:
// 1. OAuth2 with read scope, OR
// 2. API key (header) + Basic auth, OR
// 3. Bearer token + API
// key (cookie)
func (c *Client) GetProtectedResource(ctx context.Context, apiKeyCookieToken string, apiKeyHeaderToken string, basicAuthUsername string, basicAuthPassword string, bearerAuthToken string) error {
	if apiKeyCookieToken == "" {
		apiKeyCookieToken = c.apiKeyCookieToken
	}

	if apiKeyHeaderToken == "" {
		apiKeyHeaderToken = c.apiKeyHeaderToken
	}

	if basicAuthUsername == "" {
		basicAuthUsername = c.basicAuthUsername
		basicAuthPassword = c.basicAuthPassword
	}

	if bearerAuthToken == "" {
		bearerAuthToken = c.bearerAuthToken
	}

	if !((apiKeyHeaderToken != "" && basicAuthUsername != "") || (apiKeyCookieToken != "" && bearerAuthToken != "")) {
		return ErrMissingAuthToken
	}

	u := c.baseURL + "/protected-resource"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	if apiKeyCookieToken != "" {
		req.AddCookie(&http.Cookie{Name: "cookie_name", Value: apiKeyCookieToken})
	}

	if apiKeyHeaderToken != "" {
		req.Header.Set("X-API-Key", apiKeyHeaderToken)
	}

	if basicAuthUsername != "" {
		req.SetBasicAuth(basicAuthUsername, basicAuthPassword)
	}

	if bearerAuthToken != "" {
		req.Header.Set("Authorization", "Bearer "+bearerAuthToken)
	}

	resp, err := c.doer.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	return nil
}

// GetPublicStatus
// Get API status
// Public endpoint that requires no authentication
func (c *Client) GetPublicStatus(ctx context.Context) (*GetPublicStatusResponse, error) {
	u := c.baseURL + "/public/status"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	resp, err := c.doer.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	var out GetPublicStatusResponse
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetCurrentUser
// Get current user
// Requires either API key in header OR bearer token
func (c *Client) GetCurrentUser(ctx context.Context, apiKeyHeaderToken string, bearerAuthToken string, oauth2ExampleToken *oauth2.Token) (*User, error) {
	if apiKeyHeaderToken == "" {
		apiKeyHeaderToken = c.apiKeyHeaderToken
	}

	if bearerAuthToken == "" {
		bearerAuthToken = c.bearerAuthToken
	}

	if !((apiKeyHeaderToken != "") || (bearerAuthToken != "") || (oauth2ExampleToken != nil)) {
		return nil, ErrMissingAuthToken
	}

	u := c.baseURL + "/users/me"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	if apiKeyHeaderToken != "" {
		req.Header.Set("X-API-Key", apiKeyHeaderToken)
	}

	if bearerAuthToken != "" {
		req.Header.Set("Authorization", "Bearer "+bearerAuthToken)
	}
	doer := c.doer

	if oauth2ExampleToken != nil {
		doer = c.oauth2ExampleConfig.Client(context.WithValue(ctx, oauth2.HTTPClient, c.doer), oauth2ExampleToken)
	}

	resp, err := doer.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	var out User
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetUserProfile
// Get user profile
// Requires bearer token authentication
func (c *Client) GetUserProfile(ctx context.Context, bearerAuthToken string) (*User, error) {
	if bearerAuthToken == "" {
		bearerAuthToken = c.bearerAuthToken
	}

	if !(bearerAuthToken != "") {
		return nil, ErrMissingAuthToken
	}

	u := c.baseURL + "/users/profile"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	if bearerAuthToken != "" {
		req.Header.Set("Authorization", "Bearer "+bearerAuthToken)
	}

	resp, err := c.doer.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	var out User
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
