// Code generated by foji (dev build), template: foji/openapi/client.go.tpl; DO NOT EDIT.

package auth

import (
	"context"
	"io"
	"net/http"
	"net/url"

	"github.com/bir/iken/httputil"
	"tests/example"
)

type (
	ClientAuthenticator         = httputil.ClientAuthenticateFunc[*example.ExampleAuth]
	ClientTokenAuthenticator    = httputil.ClientTokenAuthenticatorFunc[*example.ExampleAuth]
	ClientBasicAuthenticator    = httputil.ClientBasicAuthenticatorFunc[*example.ExampleAuth]
	ClientCookieAuthenticator   = httputil.ClientCookieAuthenticatorFunc[*example.ExampleAuth]
	ClientWrappingAuthenticator = httputil.ClientWrappingAuthenticatorFunc[*example.ExampleAuth]
	ClientSecurityGroup         = httputil.ClientSecurityGroup[*example.ExampleAuth]
	ClientSecurityGroups        = httputil.ClientSecurityGroups[*example.ExampleAuth]
)

type Client struct {
	baseURL                            string
	httpClient                         *http.Client
	apiKeyCookieAuth                   ClientAuthenticator
	apiKeyHeaderAuth                   ClientAuthenticator
	apiKeyQueryAuth                    ClientAuthenticator
	basicAuthAuth                      ClientAuthenticator
	bearerAuthAuth                     ClientAuthenticator
	oauth2ClientCredentialsExampleAuth ClientAuthenticator
	oauth2ExampleAuth                  ClientAuthenticator
	openIdconnectAuth                  ClientAuthenticator
	rawAuth                            ClientAuthenticator
	listAdminUsersSecurity             ClientSecurityGroups
	queryDataWithApiKeySecurity        ClientSecurityGroups
	createDocumentSecurity             ClientSecurityGroups
	getProtectedResourceSecurity       ClientSecurityGroups
	getCurrentUserSecurity             ClientSecurityGroups
}

func NewClient(baseURL string, httpClient *http.Client, apiKeyCookieAuth ClientCookieAuthenticator, apiKeyHeaderAuth ClientTokenAuthenticator, apiKeyQueryAuth ClientTokenAuthenticator, basicAuthAuth ClientBasicAuthenticator, bearerAuthAuth ClientTokenAuthenticator, oauth2ClientCredentialsExampleAuth ClientWrappingAuthenticator, oauth2ExampleAuth ClientWrappingAuthenticator, openIdconnectAuth ClientWrappingAuthenticator, rawAuth ClientAuthenticator) *Client {
	c := &Client{
		baseURL:                            baseURL,
		httpClient:                         httpClient,
		apiKeyCookieAuth:                   httputil.CookieClientAuth(apiKeyCookieAuth),
		apiKeyHeaderAuth:                   httputil.HeaderClientAuth("X-API-Key", apiKeyHeaderAuth),
		apiKeyQueryAuth:                    httputil.QueryClientAuth("query_key_name", apiKeyQueryAuth),
		basicAuthAuth:                      httputil.BasicClientAuth(basicAuthAuth),
		bearerAuthAuth:                     httputil.BearerClientAuth("Authorization", bearerAuthAuth),
		oauth2ClientCredentialsExampleAuth: httputil.WrapClientAuth(oauth2ClientCredentialsExampleAuth),
		oauth2ExampleAuth:                  httputil.WrapClientAuth(oauth2ExampleAuth),
		openIdconnectAuth:                  httputil.WrapClientAuth(openIdconnectAuth),
		rawAuth:                            rawAuth,
	}

	c.listAdminUsersSecurity = ClientSecurityGroups{
		ClientSecurityGroup{c.apiKeyHeaderAuth, c.bearerAuthAuth},
	}

	c.queryDataWithApiKeySecurity = ClientSecurityGroups{
		ClientSecurityGroup{c.apiKeyHeaderAuth},
		ClientSecurityGroup{c.apiKeyQueryAuth},
		ClientSecurityGroup{c.apiKeyCookieAuth},
		ClientSecurityGroup{c.rawAuth},
	}

	c.createDocumentSecurity = ClientSecurityGroups{
		ClientSecurityGroup{c.apiKeyHeaderAuth, c.bearerAuthAuth},
	}

	c.getProtectedResourceSecurity = ClientSecurityGroups{
		ClientSecurityGroup{c.apiKeyHeaderAuth, c.basicAuthAuth},
		ClientSecurityGroup{c.apiKeyCookieAuth, c.bearerAuthAuth},
	}

	c.getCurrentUserSecurity = ClientSecurityGroups{
		ClientSecurityGroup{c.apiKeyHeaderAuth},
		ClientSecurityGroup{c.bearerAuthAuth},
		ClientSecurityGroup{c.oauth2ExampleAuth},
	}

	return c
}

// ListAdminUsers
// List all users (admin only)
// Requires both API key AND bearer token with admin scope
func (c *Client) ListAdminUsers(ctx context.Context, user *example.ExampleAuth) ([]User, error) {
	u := c.baseURL + "/admin/users"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient
	httpClient, err = c.listAdminUsersSecurity.Auth(req, httpClient, user)
	if err != nil {
		return nil, err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out []User
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return out, nil
}

// QueryDataWithApiKey
// Query data with API key
// Accepts API key in header, query parameter, or cookie
func (c *Client) QueryDataWithApiKey(ctx context.Context, user *example.ExampleAuth, query *string) error {
	u := c.baseURL + "/data/query"
	queryParams := url.Values{}
	if query != nil {
		queryParams.Set("query", (*query))
	}

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.queryDataWithApiKeySecurity.Auth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// ListDocuments
// List documents
// Requires basic authentication
func (c *Client) ListDocuments(ctx context.Context, user *example.ExampleAuth) error {
	u := c.baseURL + "/documents"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.basicAuthAuth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// CreateDocument
// Create document
// Requires API key with bearer token
func (c *Client) CreateDocument(ctx context.Context, user *example.ExampleAuth) error {
	u := c.baseURL + "/documents"

	req, err := http.NewRequestWithContext(ctx, "POST", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.createDocumentSecurity.Auth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// Overview
// System overview
// Requires OAuth client credentials
func (c *Client) Overview(ctx context.Context, user *example.ExampleAuth) error {
	u := c.baseURL + "/overview"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.oauth2ClientCredentialsExampleAuth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// GetDetailedProfile
// Get detailed profile
// Requires OpenID Connect authentication
func (c *Client) GetDetailedProfile(ctx context.Context, user *example.ExampleAuth) error {
	u := c.baseURL + "/profile/detailed"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.openIdconnectAuth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// GetProtectedResource
// Access protected resource
// Multiple authentication options:
// 1. OAuth2 with read scope, OR
// 2. API key (header) + Basic auth, OR
// 3. Bearer token + API
// key (cookie)
func (c *Client) GetProtectedResource(ctx context.Context, user *example.ExampleAuth) error {
	u := c.baseURL + "/protected-resource"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.getProtectedResourceSecurity.Auth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// GetPublicStatus
// Get API status
// Public endpoint that requires no authentication
func (c *Client) GetPublicStatus(ctx context.Context) (*GetPublicStatusResponse, error) {
	u := c.baseURL + "/public/status"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out GetPublicStatusResponse
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetCurrentUser
// Get current user
// Requires either API key in header OR bearer token
func (c *Client) GetCurrentUser(ctx context.Context, user *example.ExampleAuth) (*User, error) {
	u := c.baseURL + "/users/me"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient
	httpClient, err = c.getCurrentUserSecurity.Auth(req, httpClient, user)
	if err != nil {
		return nil, err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out User
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetUserProfile
// Get user profile
// Requires bearer token authentication
func (c *Client) GetUserProfile(ctx context.Context, user *example.ExampleAuth) (*User, error) {
	u := c.baseURL + "/users/profile"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient
	httpClient, err = c.bearerAuthAuth(req, httpClient, user)
	if err != nil {
		return nil, err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out User
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
