// Code generated by foji, template: foji/openapi/client.go.tpl; DO NOT EDIT.

package csvresponse

import (
	"context"
	"fmt"
	"io"
	"net/http"

	"github.com/bir/iken/httputil"
)

type (
	ClientAuthenticator         = httputil.ClientAuthenticateFunc[*ExampleAuth]
	ClientTokenAuthenticator    = httputil.ClientTokenAuthenticatorFunc[*ExampleAuth]
	ClientBasicAuthenticator    = httputil.ClientBasicAuthenticatorFunc[*ExampleAuth]
	ClientCookieAuthenticator   = httputil.ClientCookieAuthenticatorFunc[*ExampleAuth]
	ClientWrappingAuthenticator = httputil.ClientWrappingAuthenticatorFunc[*ExampleAuth]
)

type Client struct {
	baseURL        string
	httpClient     *http.Client
	headerAuthAuth ClientAuthenticator
}

func NewClient(baseURL string, httpClient *http.Client, headerAuthAuth ClientTokenAuthenticator) *Client {
	c := &Client{
		baseURL:        baseURL,
		httpClient:     httpClient,
		headerAuthAuth: httputil.HeaderClientAuth("Authorization", headerAuthAuth),
	}

	return c
}

// GetByteCsv
func (c *Client) GetByteCsv(ctx context.Context) ([]byte, error) {
	u := c.baseURL + "/bytesCSV"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	out, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	return out, nil
}

// GetReaderCsv
func (c *Client) GetReaderCsv(ctx context.Context) (io.Reader, error) {
	u := c.baseURL + "/readerCSV"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		defer resp.Body.Close()
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return resp.Body, nil
}

// GetStringCsv
func (c *Client) GetStringCsv(ctx context.Context) (string, error) {
	u := c.baseURL + "/stringCSV"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return "", err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return "", httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	out, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}

	return string(out), nil
}
