// Code generated by foji (dev build), template: foji/openapi/client.go.tpl; DO NOT EDIT.

package csvresponse

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
)

type Doer interface {
	Do(*http.Request) (*http.Response, error)
}

type ClientOption func(*Client)

type Client struct {
	baseURL         string
	doer            Doer
	headerAuthToken string
}

func NewClient(baseURL string, doer Doer, opts ...ClientOption) *Client {
	c := &Client{baseURL: baseURL, doer: doer}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

func WithHeaderAuthToken(token string) ClientOption {
	return func(c *Client) {
		c.headerAuthToken = token
	}
}

var ErrMissingAuthToken = errors.New("missing auth token")

type APIError struct {
	StatusCode int
	Status     string
	Body       []byte
}

func (e *APIError) Error() string {
	return fmt.Sprintf("%d %s: %s", e.StatusCode, e.Status, string(e.Body))
}

// GetByteCsv
func (c *Client) GetByteCsv(ctx context.Context) ([]byte, error) {
	u := c.baseURL + "/bytesCSV"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	resp, err := c.doer.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	out, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read response: %w", err)
	}

	return out, nil
}

// GetReaderCsv
func (c *Client) GetReaderCsv(ctx context.Context) (io.Reader, error) {
	u := c.baseURL + "/readerCSV"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	resp, err := c.doer.Do(req)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		defer resp.Body.Close()
		errBody, _ := io.ReadAll(resp.Body)

		return nil, &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	return resp.Body, nil
}

// GetStringCsv
func (c *Client) GetStringCsv(ctx context.Context) (string, error) {
	u := c.baseURL + "/stringCSV"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return "", err
	}

	resp, err := c.doer.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return "", &APIError{StatusCode: resp.StatusCode, Status: resp.Status, Body: errBody}
	}

	out, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("read response: %w", err)
	}

	return string(out), nil
}
