{{- define "toStr" -}}
    {{- $e := .RuntimeParams.expr -}}
    {{- $t := .RuntimeParams.goType -}}
    {{- if .RuntimeParams.isEnum -}}{{ $e }}.String()
    {{- else if eq $t "string" -}}{{ $e }}
    {{- else if eq $t "time.Time" -}}{{ $e }}.Format(time.RFC3339)
    {{- else if eq $t "uuid.UUID" -}}{{ $e }}.String()
    {{- else if eq $t "bool" -}}strconv.FormatBool({{ $e }})
    {{- else if eq $t "int" -}}strconv.Itoa({{ $e }})
    {{- else if eq $t "int32" -}}strconv.FormatInt(int64({{ $e }}), 10)
    {{- else if eq $t "int16" -}}strconv.FormatInt(int64({{ $e }}), 10)
    {{- else if eq $t "int64" -}}strconv.FormatInt({{ $e }}, 10)
    {{- else if eq $t "float32" -}}strconv.FormatFloat(float64({{ $e }}), 'f', -1, 32)
    {{- else if eq $t "float64" -}}strconv.FormatFloat({{ $e }}, 'f', -1, 64)
    {{- else -}}fmt.Sprintf("%v", {{ $e }})
    {{- end -}}
{{- end -}}

{{- /* clientAuth classifies a security scheme and emits the fragment for the requested mode:
       param (NewClient argument), construct (Client field initializer) or apply (per-request call). */}}
{{- define "clientAuth" -}}
    {{- $scheme := .RuntimeParams.scheme -}}
    {{- $mode := .RuntimeParams.mode -}}
    {{- $s := index $.API.Components.SecuritySchemes $scheme -}}
    {{- $v := $s.Value -}}
    {{- $c := camel $scheme -}}
    {{- $kind := "header" -}}
    {{- if $.SecurityHasExtension $s "x-raw-client-auth" -}}{{ $kind = "raw" }}
    {{- else if eq $v.Type "http" -}}
        {{- if eq $v.Scheme "basic" -}}{{ $kind = "basic" }}{{- else -}}{{ $kind = "bearer" }}{{- end -}}
    {{- else if or (eq $v.Type "oauth2") (eq $v.Type "openIdConnect") -}}{{ $kind = "wrap" }}
    {{- else if eq $v.In "query" -}}{{ $kind = "query" }}
    {{- else if eq $v.In "cookie" -}}{{ $kind = "cookie" }}
    {{- else -}}{{ $kind = "header" }}{{- end -}}

    {{- if eq $mode "param" -}}
        {{- if eq $kind "raw" -}}{{ $c }}Auth ClientAuthenticator
        {{- else if eq $kind "basic" -}}{{ $c }}Auth ClientBasicAuthenticator
        {{- else if eq $kind "cookie" -}}{{ $c }}Auth ClientCookieAuthenticator
        {{- else if eq $kind "wrap" -}}{{ $c }}Auth ClientWrappingAuthenticator
        {{- else -}}{{ $c }}Auth ClientTokenAuthenticator
        {{- end -}}
    {{- else if eq $mode "construct" }}
        {{- if eq $kind "raw" }}
		{{ $c }}Auth: {{ $c }}Auth,
        {{- else if eq $kind "header" }}
		{{ $c }}Auth: httputil.HeaderClientAuth("{{ $v.Name }}", {{ $c }}Auth),
        {{- else if eq $kind "query" }}
		{{ $c }}Auth: httputil.QueryClientAuth("{{ $v.Name }}", {{ $c }}Auth),
        {{- else if eq $kind "bearer" }}
		{{ $c }}Auth: httputil.BearerClientAuth("Authorization", {{ $c }}Auth),
        {{- else if eq $kind "basic" }}
		{{ $c }}Auth: httputil.BasicClientAuth({{ $c }}Auth),
        {{- else if eq $kind "cookie" }}
		{{ $c }}Auth: httputil.CookieClientAuth({{ $c }}Auth),
        {{- else if eq $kind "wrap" }}
		{{ $c }}Auth: httputil.WrapClientAuth({{ $c }}Auth),
        {{- end -}}
    {{- else if eq $mode "apply" }}
	httpClient, err = c.{{ $c }}Auth(req, httpClient, user)
	if err != nil {
		return {{ $.RuntimeParams.errRet }}err
	}
    {{- end -}}
{{- end -}}

{{- define "clientMethodSignature"}}
    {{- $path := .RuntimeParams.path -}}
    {{- $op := .RuntimeParams.op -}}
    {{- $package := .RuntimeParams.package -}}
    {{- $body := .GetRequestBody $op -}}
    {{- if $.OpSecuritySchemes $op }} user *{{ $.CheckPackage ($.Params.GetWithDefault "ClientAuth" "") $package }},{{ end }}
    {{- range $param := $.OpParams $path $op -}}
        {{- $name := print $op.OperationID " " $param.Value.Name -}}
        {{- if notEmpty $param.Ref }}{{ $name = trimPrefix "#/components/parameters/" $param.Ref }}{{ end -}}
        {{ goToken (camel $param.Value.Name) -}}
        {{- if $.ParamIsOptionalType $param }} *{{ end }} {{ $.GetType $package $name $param.Value.Schema }},
    {{- end -}}
    {{- if isNotNil $body}}
        {{- $type := $.GetType $package (print $op.OperationID " Request") $body.Schema }} body {{ $type  -}}
    {{- end -}}
    ) (
    {{- $response := $.GetOpHappyResponseType $package $op}}
    {{- if notEmpty $response}}{{ $.CheckPackage $response $package}}, {{ end }}error)
{{- end -}}

{{- $package := $.PackageName }}
{{- $clientAuth := $.Params.GetWithDefault "ClientAuth" "" }}

// Code generated by foji {{ version }}, template: {{ templateFile }}; DO NOT EDIT.

package {{ $package }}

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"strconv"
	"strings"

	"github.com/bir/iken/httputil"
{{- .CheckAllTypes $package $clientAuth -}}
{{- range .GoImports }}
	"{{ . }}"
{{- end }}
)

{{ if .HasAuthentication -}}
{{ .ErrorIf (empty $clientAuth) "params.ClientAuth" -}}

type (
	ClientAuthenticator         = httputil.ClientAuthenticateFunc[*{{ $.CheckPackage $clientAuth $package }}]
	ClientTokenAuthenticator    = httputil.ClientTokenAuthenticatorFunc[*{{ $.CheckPackage $clientAuth $package }}]
	ClientBasicAuthenticator    = httputil.ClientBasicAuthenticatorFunc[*{{ $.CheckPackage $clientAuth $package }}]
	ClientCookieAuthenticator   = httputil.ClientCookieAuthenticatorFunc[*{{ $.CheckPackage $clientAuth $package }}]
	ClientWrappingAuthenticator = httputil.ClientWrappingAuthenticatorFunc[*{{ $.CheckPackage $clientAuth $package }}]

{{- if .HasComplexAuth }}
	ClientSecurityGroup  = httputil.ClientSecurityGroup[*{{ $.CheckPackage $clientAuth $package }}]
	ClientSecurityGroups = httputil.ClientSecurityGroups[*{{ $.CheckPackage $clientAuth $package }}]
{{- end }}
)

{{ end -}}

type Client struct {
	baseURL    string
	httpClient *http.Client
{{- range $security, $value := .API.Components.SecuritySchemes }}
	{{ camel $security }}Auth ClientAuthenticator
{{- end }}
{{- range $name, $path := .API.Paths.Map }}
    {{- range $verb, $op := $path.Operations }}
        {{- if not ($.IsSimpleAuth $op) }}
	{{ camel $op.OperationID}}Security ClientSecurityGroups
        {{- end}}
    {{- end}}
{{- end}}
}

func NewClient(baseURL string, httpClient *http.Client
{{- range $security, $value := .API.Components.SecuritySchemes }}, {{ template "clientAuth" ($.WithParams "scheme" $security "mode" "param") }}{{- end }}) *Client {
	c := &Client{
		baseURL:    baseURL,
		httpClient: httpClient,
{{- range $security, $value := .API.Components.SecuritySchemes }}{{ template "clientAuth" ($.WithParams "scheme" $security "mode" "construct") }}{{- end }}
	}
{{- range $name, $path := .API.Paths.Map }}
    {{- range $verb, $op := $path.Operations }}
        {{- if not ($.IsSimpleAuth $op) }}

	c.{{ camel $op.OperationID}}Security = ClientSecurityGroups{
            {{- range $securityGroup := $.OpSecurity $op }}
		ClientSecurityGroup{
                {{- range $security, $scopes := $securityGroup -}}
			c.{{ camel $security }}Auth,
                {{- end -}}
		},
            {{- end }}
	}
        {{- end}}
    {{- end}}
{{- end}}

	return c
}

{{- range $name, $path := .API.Paths.Map }}
    {{- range $verb, $op := $path.Operations }}
        {{- $body := $.GetRequestBody $op }}
        {{- $opResponse := $.GetOpHappyResponse $package $op }}
        {{- $respType := $opResponse.GoType }}
        {{- $errRet := "" }}
        {{- if notEmpty $respType }}{{ if eq $respType "string" }}{{ $errRet = "\"\", " }}{{ else }}{{ $errRet = "nil, " }}{{ end }}{{ end }}

{{ goDoc (pascal $op.OperationID) }}
{{- goDoc $op.Summary }}
{{- goDoc $op.Description }}
func (c *Client) {{ pascal $op.OperationID }}(ctx context.Context,
    {{- template "clientMethodSignature" ($.WithParams "op" $op "package" $package "path" $path) }} {
	u := c.baseURL + "{{ $name }}"
        {{- $hasQuery := false }}
        {{- range $param := $.OpParams $path $op }}{{ if eq $param.Value.In "query" }}{{ $hasQuery = true }}{{ end }}{{ end }}
        {{- if $hasQuery }}
	queryParams := url.Values{}
        {{- end }}
        {{- range $param := $.OpParams $path $op }}
            {{- $pName := $param.Value.Name }}
            {{- $var := goToken (camel $pName) }}
            {{- $tName := print $op.OperationID " " $pName }}
            {{- if notEmpty $param.Ref }}{{ $tName = trimPrefix "#/components/parameters/" $param.Ref }}{{ end }}
            {{- $goType := $.GetType $package $tName $param.Value.Schema }}
            {{- $isArray := $param.Value.Schema.Value.Type.Is "array" }}
            {{- $isEnum := $.ParamIsEnum $param }}
            {{- if $isArray }}
                {{- $elemType := $.StripArray $goType }}
                {{- $isArrayEnum := $.ParamIsEnumArray $param }}
                {{- if eq $param.Value.In "query" }}
	for _, v := range {{ $var }} {
		queryParams.Add("{{ $pName }}", {{ template "toStr" ($.WithParams "expr" "v" "goType" $elemType "isEnum" $isArrayEnum) }})
	}
                {{- end }}
            {{- else if $.ParamIsOptionalType $param }}
                {{- $deref := print "(*" $var ")" }}
	if {{ $var }} != nil {
                {{- if eq $param.Value.In "query" }}
		queryParams.Set("{{ $pName }}", {{ template "toStr" ($.WithParams "expr" $deref "goType" $goType "isEnum" $isEnum) }})
                {{- end }}
	}
            {{- else }}
                {{- if eq $param.Value.In "path" }}
	u = strings.Replace(u, "{{ printf "{%s}" $pName }}", url.PathEscape({{ template "toStr" ($.WithParams "expr" $var "goType" $goType "isEnum" $isEnum) }}), 1)
                {{- else if eq $param.Value.In "query" }}
	queryParams.Set("{{ $pName }}", {{ template "toStr" ($.WithParams "expr" $var "goType" $goType "isEnum" $isEnum) }})
                {{- end }}
            {{- end }}
        {{- end }}
        {{- if $hasQuery }}

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}
        {{- end }}

        {{- if isNotNil $body }}
            {{- if $body.IsJson }}

	buf, err := json.Marshal(body)
	if err != nil {
		return {{ $errRet }}fmt.Errorf("marshal request body: %w", err)
	}

	reqBody := bytes.NewReader(buf)
	contentType := "application/json"
            {{- else if $body.IsText }}

	reqBody := strings.NewReader(body)
	contentType := "text/plain"
            {{- else if $body.IsForm }}

	form := url.Values{}
                {{- range $field, $schemaProp := $.SchemaProperties $body.Schema }}
                    {{- $fGoType := $.GetType $package (print $op.OperationID " " $field) $schemaProp }}
                    {{- $fVar := print "body." (pascal $field) }}
                    {{- $fIsPtr := and (not ($.IsRequiredProperty $field $body.Schema)) $schemaProp.Value.Nullable }}
                    {{- if $schemaProp.Value.Type.Is "array" }}
	for _, v := range {{ $fVar }} {
		form.Add("{{ $field }}", {{ template "toStr" ($.WithParams "expr" "v" "goType" ($.StripArray $fGoType) "isEnum" ($.SchemaIsEnumArray $schemaProp)) }})
	}
                    {{- else if $fIsPtr }}
	if {{ $fVar }} != nil {
		form.Set("{{ $field }}", {{ template "toStr" ($.WithParams "expr" (print "(*" $fVar ")") "goType" $fGoType "isEnum" ($.SchemaIsEnum $schemaProp)) }})
	}
                    {{- else }}
	form.Set("{{ $field }}", {{ template "toStr" ($.WithParams "expr" $fVar "goType" $fGoType "isEnum" ($.SchemaIsEnum $schemaProp)) }})
                    {{- end }}
                {{- end }}

	reqBody := strings.NewReader(form.Encode())
	contentType := "application/x-www-form-urlencoded"
            {{- else if $body.IsMultipartForm }}

	var bodyBuf bytes.Buffer

	mw := multipart.NewWriter(&bodyBuf)
                {{- range $field, $schemaProp := $.SchemaProperties $body.Schema }}
                    {{- $fGoType := $.GetType $package (print $op.OperationID " " $field) $schemaProp }}
                    {{- $fVar := print "body." (pascal $field) }}
                    {{- $fRequired := $.IsRequiredProperty $field $body.Schema }}
                    {{- $fIsPtr := and (not $fRequired) $schemaProp.Value.Nullable }}
                    {{- if eq $fGoType "forms.File" }}
	{{ if not $fRequired }}if {{ $fVar }}.File != nil { {{ end -}}
	{
		part, err := mw.CreateFormFile("{{ $field }}", {{ $fVar }}.Filename)
		if err != nil {
			return {{ $errRet }}fmt.Errorf("multipart file {{ $field }}: %w", err)
		}

		if _, err := io.Copy(part, {{ $fVar }}.File); err != nil {
			return {{ $errRet }}fmt.Errorf("multipart file {{ $field }}: %w", err)
		}
	}
	{{- if not $fRequired }} }{{ end }}
                    {{- else if $schemaProp.Value.Type.Is "array" }}
	for _, v := range {{ $fVar }} {
		if err := mw.WriteField("{{ $field }}", {{ template "toStr" ($.WithParams "expr" "v" "goType" ($.StripArray $fGoType) "isEnum" ($.SchemaIsEnumArray $schemaProp)) }}); err != nil {
			return {{ $errRet }}fmt.Errorf("multipart field {{ $field }}: %w", err)
		}
	}
                    {{- else if $fIsPtr }}
	if {{ $fVar }} != nil {
		if err := mw.WriteField("{{ $field }}", {{ template "toStr" ($.WithParams "expr" (print "(*" $fVar ")") "goType" $fGoType "isEnum" ($.SchemaIsEnum $schemaProp)) }}); err != nil {
			return {{ $errRet }}fmt.Errorf("multipart field {{ $field }}: %w", err)
		}
	}
                    {{- else }}
	if err := mw.WriteField("{{ $field }}", {{ template "toStr" ($.WithParams "expr" $fVar "goType" $fGoType "isEnum" ($.SchemaIsEnum $schemaProp)) }}); err != nil {
		return {{ $errRet }}fmt.Errorf("multipart field {{ $field }}: %w", err)
	}
                    {{- end }}
                {{- end }}

	if err := mw.Close(); err != nil {
		return {{ $errRet }}fmt.Errorf("multipart close: %w", err)
	}

	reqBody := &bodyBuf
	contentType := mw.FormDataContentType()
            {{- end }}
        {{- end }}

	req, err := http.NewRequestWithContext(ctx, "{{ $verb }}", u, {{ if isNotNil $body }}reqBody{{ else }}http.NoBody{{ end }})
	if err != nil {
		return {{ $errRet }}err
	}
        {{- if isNotNil $body }}

	req.Header.Set("Content-Type", contentType)
        {{- end }}
        {{- range $param := $.OpParams $path $op }}
            {{- $pName := $param.Value.Name }}
            {{- $var := goToken (camel $pName) }}
            {{- $tName := print $op.OperationID " " $pName }}
            {{- if notEmpty $param.Ref }}{{ $tName = trimPrefix "#/components/parameters/" $param.Ref }}{{ end }}
            {{- $goType := $.GetType $package $tName $param.Value.Schema }}
            {{- $isEnum := $.ParamIsEnum $param }}
            {{- if eq $param.Value.In "header" }}
                {{- if $.ParamIsOptionalType $param }}

	if {{ $var }} != nil {
		req.Header.Set("{{ $pName }}", {{ template "toStr" ($.WithParams "expr" (print "(*" $var ")") "goType" $goType "isEnum" $isEnum) }})
	}
                {{- else }}

	req.Header.Set("{{ $pName }}", {{ template "toStr" ($.WithParams "expr" $var "goType" $goType "isEnum" $isEnum) }})
                {{- end }}
            {{- else if eq $param.Value.In "cookie" }}
                {{- if $.ParamIsOptionalType $param }}

	if {{ $var }} != nil {
		req.AddCookie(&http.Cookie{Name: "{{ $pName }}", Value: {{ template "toStr" ($.WithParams "expr" (print "(*" $var ")") "goType" $goType "isEnum" $isEnum) }}})
	}
                {{- else }}

	req.AddCookie(&http.Cookie{Name: "{{ $pName }}", Value: {{ template "toStr" ($.WithParams "expr" $var "goType" $goType "isEnum" $isEnum) }}})
                {{- end }}
            {{- end }}
        {{- end }}

	httpClient := c.httpClient
        {{- if $.IsSimpleAuth $op }}
        {{- range $scheme := $.OpSecuritySchemes $op }}{{ template "clientAuth" ($.WithParams "scheme" $scheme "mode" "apply" "errRet" $errRet) }}{{- end }}
        {{- else }}
	httpClient, err = c.{{ camel $op.OperationID}}Security.Auth(req, httpClient, user)
	if err != nil {
		return {{ $errRet }}err
	}
        {{- end }}

	resp, err := httpClient.Do(req)
	if err != nil {
		return {{ $errRet }}err
	}
        {{- if ne $respType "io.Reader" }}
	defer resp.Body.Close()
        {{- end }}

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
        {{- if eq $respType "io.Reader" }}
		defer resp.Body.Close()
        {{- end }}
		errBody, _ := io.ReadAll(resp.Body)

		return {{ $errRet }}httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

        {{- if eq $respType "" }}

	return nil
        {{- else if $opResponse.MimeType.IsJson }}
            {{- if hasPrefix "*" $respType }}

	var out {{ trimPrefix "*" $respType }}
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return {{ $errRet }}err
	}

	return &out, nil
            {{- else }}

	var out {{ $respType }}
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return {{ $errRet }}err
	}

	return out, nil
            {{- end }}
        {{- else if eq $respType "io.Reader" }}

	return resp.Body, nil
        {{- else if eq $respType "[]byte" }}

	out, err := io.ReadAll(resp.Body)
	if err != nil {
		return {{ $errRet }}fmt.Errorf("read response: %w", err)
	}

	return out, nil
        {{- else if hasPrefix "*" $respType }}

	out, err := io.ReadAll(resp.Body)
	if err != nil {
		return {{ $errRet }}fmt.Errorf("read response: %w", err)
	}

	v := {{ trimPrefix "*" $respType }}(out)

	return &v, nil
        {{- else }}

	out, err := io.ReadAll(resp.Body)
	if err != nil {
		return {{ $errRet }}fmt.Errorf("read response: %w", err)
	}

	return {{ $respType }}(out), nil
        {{- end }}
}
    {{- end }}
{{- end }}
