// Code generated by foji, template: foji/openapi/model.go.tpl; DO NOT EDIT.

package example

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"net/http"
	"regexp"
	"time"

	"github.com/bir/iken/forms"
	"github.com/bir/iken/validation"
	"github.com/google/uuid"
)

var ErrExampleMissingRequiredField = errors.New("missing required field")

// Component Schemas

// ExampleBar
//
// OpenAPI Component Schema: Bar
type ExampleBar struct {
	Bars string `json:"bars,omitempty,omitzero"`
}

var exampleBarBarsPattern = regexp.MustCompile(`(b1|b2)`)

func (p *ExampleBar) UnmarshalJSON(b []byte) error {
	var err error

	type ExampleBarJSON ExampleBar
	var parseObject ExampleBarJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleBar.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleBar(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleBar) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleBar // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleBar.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleBar) Validate() error {
	var err validation.Errors

	p.ValidateBars(&err)

	return err.GetErr()
}

func (p ExampleBar) ValidateBars(err *validation.Errors) {
	if len(p.Bars) < 2 {
		_ = err.Add("bars", "length must be >= 2")
	}

	if p.Bars != "" && !exampleBarBarsPattern.MatchString(string(p.Bars)) {
		_ = err.Add("bars", `must match "(b1|b2)"`)
	}
}

// ExampleBuzz
//
// OpenAPI Component Schema: Buzz
type ExampleBuzz struct {
	Buzzes string `json:"buzzes,omitempty,omitzero"`
}

// ExampleDefaultWithoutRequired
//
// OpenAPI Component Schema: DefaultWithoutRequired
type ExampleDefaultWithoutRequired struct {
	F1 string `json:"f1,omitempty,omitzero"`
}

func (p *ExampleDefaultWithoutRequired) UnmarshalJSON(b []byte) error {
	var err error
	var requiredCheck map[string]any

	err = json.Unmarshal(b, &requiredCheck)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleDefaultWithoutRequired.UnmarshalJSON Required: `%v`: %w", string(b), err)}
	}

	var validationErrors validation.Errors

	if validationErrors != nil {
		return validationErrors.GetErr()
	}

	type ExampleDefaultWithoutRequiredJSON ExampleDefaultWithoutRequired
	var parseObject ExampleDefaultWithoutRequiredJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleDefaultWithoutRequired.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleDefaultWithoutRequired(parseObject)

	if _, ok := requiredCheck["f1"]; !ok {
		v.F1 = "surprise!"
	}

	*p = v

	return nil
}

// ExampleExample
//
// OpenAPI Component Schema: Example
type ExampleExample struct {
	ID           uuid.UUID           `json:"id"`
	IdMaybe      *uuid.UUID          `json:"idMaybe,omitempty,omitzero"`
	Name         string              `json:"name,omitempty,omitzero"`
	PlayerAlways ExamplePlayerAlways `json:"playerAlways,omitempty,omitzero"`
	PlayerID     uuid.UUID           `json:"playerId,omitempty,omitzero"`
	PlayerMaybe  *ExamplePlayerMaybe `json:"playerMaybe,omitempty,omitzero"`
}

func (p *ExampleExample) UnmarshalJSON(b []byte) error {
	var err error
	var requiredCheck map[string]any

	err = json.Unmarshal(b, &requiredCheck)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleExample.UnmarshalJSON Required: `%v`: %w", string(b), err)}
	}

	var validationErrors validation.Errors

	if _, ok := requiredCheck["id"]; !ok {
		validationErrors.Add("id", ErrExampleMissingRequiredField)
	}

	if validationErrors != nil {
		return validationErrors.GetErr()
	}

	type ExampleExampleJSON ExampleExample
	var parseObject ExampleExampleJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleExample.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleExample(parseObject)

	*p = v

	return nil
}

// ExampleExamples
//
// OpenAPI Component Schema: Examples
type ExampleExamples struct {
	List []ExampleExample `json:"list"`
}

func (p *ExampleExamples) UnmarshalJSON(b []byte) error {
	var err error
	var requiredCheck map[string]any

	err = json.Unmarshal(b, &requiredCheck)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleExamples.UnmarshalJSON Required: `%v`: %w", string(b), err)}
	}

	var validationErrors validation.Errors

	if _, ok := requiredCheck["list"]; !ok {
		validationErrors.Add("list", ErrExampleMissingRequiredField)
	}

	if validationErrors != nil {
		return validationErrors.GetErr()
	}

	type ExampleExamplesJSON ExampleExamples
	var parseObject ExampleExamplesJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleExamples.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleExamples(parseObject)

	*p = v

	return nil
}

// ExampleFoo
//
// OpenAPI Component Schema: Foo
type ExampleFoo struct {
	Foos ExampleFooString `json:"foos,omitempty,omitzero"`
}

func (p *ExampleFoo) UnmarshalJSON(b []byte) error {
	var err error

	type ExampleFooJSON ExampleFoo
	var parseObject ExampleFooJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleFoo.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleFoo(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleFoo) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleFoo // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleFoo.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleFoo) Validate() error {
	var err validation.Errors

	p.ValidateFoos(&err)

	return err.GetErr()
}

func (p ExampleFoo) ValidateFoos(err *validation.Errors) {
	if subErr := p.Foos.Validate(); subErr != nil {
		_ = err.Add("foos", subErr)
	}
}

// ExampleFooBar
//
// OpenAPI Component Schema: FooBar
type ExampleFooBar struct {
	A    string           `json:"a"`
	B    ExampleSeason    `json:"b,omitempty,omitzero"`
	Bars string           `json:"bars,omitempty,omitzero"`
	C    ExampleIntValue  `json:"c,omitempty"`
	Foos ExampleFooString `json:"foos,omitempty,omitzero"`
}

var exampleFooBarBarsPattern = regexp.MustCompile(`(b1|b2)`)

func (p *ExampleFooBar) UnmarshalJSON(b []byte) error {
	var err error
	var requiredCheck map[string]any

	err = json.Unmarshal(b, &requiredCheck)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleFooBar.UnmarshalJSON Required: `%v`: %w", string(b), err)}
	}

	var validationErrors validation.Errors

	if _, ok := requiredCheck["a"]; !ok {
		validationErrors.Add("a", ErrExampleMissingRequiredField)
	}

	if validationErrors != nil {
		return validationErrors.GetErr()
	}

	type ExampleFooBarJSON ExampleFooBar
	var parseObject ExampleFooBarJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleFooBar.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleFooBar(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleFooBar) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleFooBar // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleFooBar.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleFooBar) Validate() error {
	var err validation.Errors

	p.ValidateA(&err)
	p.ValidateBars(&err)
	p.ValidateC(&err)
	p.ValidateFoos(&err)

	return err.GetErr()
}

func (p ExampleFooBar) ValidateA(err *validation.Errors) {
	if len(p.A) < 2 {
		_ = err.Add("a", "length must be >= 2")
	}
}

func (p ExampleFooBar) ValidateBars(err *validation.Errors) {
	if len(p.Bars) < 2 {
		_ = err.Add("bars", "length must be >= 2")
	}

	if p.Bars != "" && !exampleFooBarBarsPattern.MatchString(string(p.Bars)) {
		_ = err.Add("bars", `must match "(b1|b2)"`)
	}
}

func (p ExampleFooBar) ValidateC(err *validation.Errors) {
	if subErr := p.C.Validate(); subErr != nil {
		_ = err.Add("c", subErr)
	}
}

func (p ExampleFooBar) ValidateFoos(err *validation.Errors) {
	if subErr := p.Foos.Validate(); subErr != nil {
		_ = err.Add("foos", subErr)
	}
}

// ExampleFooBarBuzz
//
// OpenAPI Component Schema: FooBarBuzz
type ExampleFooBarBuzz struct {
	A      string           `json:"a,omitempty,omitzero"`
	B      ExampleSeason    `json:"b,omitempty,omitzero"`
	Bars   string           `json:"bars,omitempty,omitzero"`
	Buzzes string           `json:"buzzes,omitempty,omitzero"`
	C      ExampleIntValue  `json:"c,omitempty"`
	Foos   ExampleFooString `json:"foos,omitempty,omitzero"`
	X      bool             `json:"x,omitempty"`
}

var exampleFooBarBuzzBarsPattern = regexp.MustCompile(`(b1|b2)`)

func (p *ExampleFooBarBuzz) UnmarshalJSON(b []byte) error {
	var err error

	type ExampleFooBarBuzzJSON ExampleFooBarBuzz
	var parseObject ExampleFooBarBuzzJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleFooBarBuzz.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleFooBarBuzz(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleFooBarBuzz) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleFooBarBuzz // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleFooBarBuzz.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleFooBarBuzz) Validate() error {
	var err validation.Errors

	p.ValidateA(&err)
	p.ValidateBars(&err)
	p.ValidateC(&err)
	p.ValidateFoos(&err)

	return err.GetErr()
}

func (p ExampleFooBarBuzz) ValidateA(err *validation.Errors) {
	if len(p.A) < 2 {
		_ = err.Add("a", "length must be >= 2")
	}
}

func (p ExampleFooBarBuzz) ValidateBars(err *validation.Errors) {
	if len(p.Bars) < 2 {
		_ = err.Add("bars", "length must be >= 2")
	}

	if p.Bars != "" && !exampleFooBarBuzzBarsPattern.MatchString(string(p.Bars)) {
		_ = err.Add("bars", `must match "(b1|b2)"`)
	}
}

func (p ExampleFooBarBuzz) ValidateC(err *validation.Errors) {
	if subErr := p.C.Validate(); subErr != nil {
		_ = err.Add("c", subErr)
	}
}

func (p ExampleFooBarBuzz) ValidateFoos(err *validation.Errors) {
	if subErr := p.Foos.Validate(); subErr != nil {
		_ = err.Add("foos", subErr)
	}
}

// string
//
// OpenAPI Component Schema: FooString
type ExampleFooString string

var exampleFooStringPattern = regexp.MustCompile(`(f1|f2)`)

func (p *ExampleFooString) UnmarshalJSON(b []byte) error {
	var err error

	type ExampleFooStringJSON ExampleFooString
	var parseObject ExampleFooStringJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleFooString.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleFooString(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleFooString) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleFooString // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleFooString.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleFooString) Validate() error {
	var err validation.Errors

	if p != "" && !exampleFooStringPattern.MatchString(string(p)) {
		_ = err.Add("", `must match "(f1|f2)"`)
	}

	return err.GetErr()
}

// int32
//
// OpenAPI Component Schema: IntValue
type ExampleIntValue int32

func (p *ExampleIntValue) UnmarshalJSON(b []byte) error {
	var err error

	type ExampleIntValueJSON ExampleIntValue
	var parseObject ExampleIntValueJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleIntValue.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleIntValue(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleIntValue) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleIntValue // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleIntValue.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleIntValue) Validate() error {
	var err validation.Errors

	if p < 2 {
		_ = err.Add("", "must be >= 2")
	}

	if p > 10 {
		_ = err.Add("", "must be <= 10")
	}

	if p%2 != 0 {
		_ = err.Add("", "must be multiple of 2")
	}

	return err.GetErr()
}

// any
// Named object
//
// OpenAPI Component Schema: NamedObject
type ExampleNamedObject any

// ExampleNotRequiredWithValidation
//
// OpenAPI Component Schema: NotRequiredWithValidation
type ExampleNotRequiredWithValidation struct {
	F1 []string `json:"f1,omitempty"`
}

func (p *ExampleNotRequiredWithValidation) UnmarshalJSON(b []byte) error {
	var err error

	type ExampleNotRequiredWithValidationJSON ExampleNotRequiredWithValidation
	var parseObject ExampleNotRequiredWithValidationJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleNotRequiredWithValidation.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleNotRequiredWithValidation(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleNotRequiredWithValidation) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleNotRequiredWithValidation // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleNotRequiredWithValidation.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleNotRequiredWithValidation) Validate() error {
	var err validation.Errors

	p.ValidateF1(&err)

	return err.GetErr()
}

func (p ExampleNotRequiredWithValidation) ValidateF1(err *validation.Errors) {
	if len(p.F1) < 2 {
		_ = err.Add("f1", "length must be >= 2")
	}
}

// ExamplePatterns
//
// OpenAPI Component Schema: Patterns
type ExamplePatterns struct {
	ID             uuid.UUID               `json:"id"`
	IdMaybe        uuid.UUID               `json:"idMaybe,omitempty,omitzero"`
	State          *string                 `json:"state,omitempty,omitzero"`
	State2         string                  `json:"state2,omitempty,omitzero"`
	State3         *string                 `json:"state3,omitempty,omitzero"`
	StateAlways    string                  `json:"stateAlways"`
	SubInt         ExampleIntValue         `json:"subInt,omitempty"`
	SubObject      ExampleSubPattern       `json:"subObject"`
	SubObjectMaybe *ExampleSubPattern      `json:"subObjectMaybe,omitempty,omitzero"`
	SubState       ExampleState            `json:"subState"`
	SubStateMaybe  *ExampleState           `json:"subStateMaybe,omitempty,omitzero"`
	SubValue       ExamplePatternsSubValue `json:"subValue,omitempty,omitzero"`
	TimeStamp      time.Time               `json:"timeStamp"`
	TimeStampMaybe time.Time               `json:"timeStampMaybe,omitempty,omitzero"`
	Value          int32                   `json:"value,omitempty"`
	ValueF         float32                 `json:"valueF,omitempty"`
	ValueFmaybe    *float32                `json:"valueFMaybe,omitempty"`
	ValueMaybe     *int32                  `json:"valueMaybe,omitempty"`
	Values         []string                `json:"values,omitempty"`
	ValuesMaybe    *[]string               `json:"valuesMaybe,omitempty"`
}

// ExamplePatternsSubValue
//
// OpenAPI ExamplePatterns inline subValue: PatternsSubValue
type ExamplePatternsSubValue struct {
	Num int32 `json:"num,omitempty"`
}

func (p *ExamplePatternsSubValue) UnmarshalJSON(b []byte) error {
	var err error

	type ExamplePatternsSubValueJSON ExamplePatternsSubValue
	var parseObject ExamplePatternsSubValueJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExamplePatternsSubValue.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExamplePatternsSubValue(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExamplePatternsSubValue) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExamplePatternsSubValue // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExamplePatternsSubValue.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExamplePatternsSubValue) Validate() error {
	var err validation.Errors

	p.ValidateNum(&err)

	return err.GetErr()
}

func (p ExamplePatternsSubValue) ValidateNum(err *validation.Errors) {
	if p.Num < 2 {
		_ = err.Add("num", "must be >= 2")
	}
}

var (
	examplePatternsStatePattern       = regexp.MustCompile(`(enabled|disabled)`)
	examplePatternsState2Pattern      = regexp.MustCompile(`(enabled|disabled)`)
	examplePatternsStateAlwaysPattern = regexp.MustCompile(`(enabled|disabled)`)
)

func (p *ExamplePatterns) UnmarshalJSON(b []byte) error {
	var err error
	var requiredCheck map[string]any

	err = json.Unmarshal(b, &requiredCheck)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExamplePatterns.UnmarshalJSON Required: `%v`: %w", string(b), err)}
	}

	var validationErrors validation.Errors

	if _, ok := requiredCheck["id"]; !ok {
		validationErrors.Add("id", ErrExampleMissingRequiredField)
	}

	if _, ok := requiredCheck["stateAlways"]; !ok {
		validationErrors.Add("stateAlways", ErrExampleMissingRequiredField)
	}

	if _, ok := requiredCheck["subObject"]; !ok {
		validationErrors.Add("subObject", ErrExampleMissingRequiredField)
	}

	if _, ok := requiredCheck["subState"]; !ok {
		validationErrors.Add("subState", ErrExampleMissingRequiredField)
	}

	if _, ok := requiredCheck["timeStamp"]; !ok {
		validationErrors.Add("timeStamp", ErrExampleMissingRequiredField)
	}

	if validationErrors != nil {
		return validationErrors.GetErr()
	}

	type ExamplePatternsJSON ExamplePatterns
	var parseObject ExamplePatternsJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExamplePatterns.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExamplePatterns(parseObject)

	if _, ok := requiredCheck["state3"]; !ok {
		var defaultVal string = "completed"
		v.State3 = &defaultVal
	}

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExamplePatterns) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExamplePatterns // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExamplePatterns.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExamplePatterns) Validate() error {
	var err validation.Errors

	p.ValidateState(&err)
	p.ValidateState2(&err)
	p.ValidateStateAlways(&err)
	p.ValidateSubInt(&err)
	p.ValidateSubObject(&err)
	p.ValidateSubObjectMaybe(&err)
	p.ValidateSubState(&err)
	p.ValidateSubStateMaybe(&err)
	p.ValidateSubValue(&err)
	p.ValidateValue(&err)
	p.ValidateValueF(&err)
	p.ValidateValueFmaybe(&err)
	p.ValidateValueMaybe(&err)
	p.ValidateValues(&err)
	p.ValidateValuesMaybe(&err)

	return err.GetErr()
}

func (p ExamplePatterns) ValidateState(err *validation.Errors) {
	if p.State == nil {
		return
	}

	if len(*p.State) < 2 {
		_ = err.Add("state", "length must be >= 2")
	}

	if len(*p.State) > 10 {
		_ = err.Add("state", "length must be <= 10")
	}

	if *p.State != "" && !examplePatternsStatePattern.MatchString(string(*p.State)) {
		_ = err.Add("state", `must match "(enabled|disabled)"`)
	}
}

func (p ExamplePatterns) ValidateState2(err *validation.Errors) {
	if p.State2 != "" && !examplePatternsState2Pattern.MatchString(string(p.State2)) {
		_ = err.Add("state2", `must match "(enabled|disabled)"`)
	}
}

func (p ExamplePatterns) ValidateStateAlways(err *validation.Errors) {
	if p.StateAlways != "" && !examplePatternsStateAlwaysPattern.MatchString(string(p.StateAlways)) {
		_ = err.Add("stateAlways", `must match "(enabled|disabled)"`)
	}
}

func (p ExamplePatterns) ValidateSubInt(err *validation.Errors) {
	if subErr := p.SubInt.Validate(); subErr != nil {
		_ = err.Add("subInt", subErr)
	}
}

func (p ExamplePatterns) ValidateSubObject(err *validation.Errors) {
	if subErr := p.SubObject.Validate(); subErr != nil {
		_ = err.Add("subObject", subErr)
	}
}

func (p ExamplePatterns) ValidateSubObjectMaybe(err *validation.Errors) {
	if p.SubObjectMaybe == nil {
		return
	}

	if p.SubObjectMaybe != nil {
		if subErr := p.SubObjectMaybe.Validate(); subErr != nil {
			_ = err.Add("subObjectMaybe", subErr)
		}
	}
}

func (p ExamplePatterns) ValidateSubState(err *validation.Errors) {
	if subErr := p.SubState.Validate(); subErr != nil {
		_ = err.Add("subState", subErr)
	}
}

func (p ExamplePatterns) ValidateSubStateMaybe(err *validation.Errors) {
	if p.SubStateMaybe == nil {
		return
	}

	if p.SubStateMaybe != nil {
		if subErr := p.SubStateMaybe.Validate(); subErr != nil {
			_ = err.Add("subStateMaybe", subErr)
		}
	}
}

func (p ExamplePatterns) ValidateSubValue(err *validation.Errors) {
	if subErr := p.SubValue.Validate(); subErr != nil {
		_ = err.Add("subValue", subErr)
	}
}

func (p ExamplePatterns) ValidateValue(err *validation.Errors) {
	if p.Value < 2 {
		_ = err.Add("value", "must be >= 2")
	}

	if p.Value > 10 {
		_ = err.Add("value", "must be <= 10")
	}

	if p.Value%2 != 0 {
		_ = err.Add("value", "must be multiple of 2")
	}
}

func (p ExamplePatterns) ValidateValueF(err *validation.Errors) {
	if p.ValueF < 2 {
		_ = err.Add("valueF", "must be >= 2")
	}

	if p.ValueF > 10 {
		_ = err.Add("valueF", "must be <= 10")
	}

	if math.Mod(float64(p.ValueF), 2) != 0 {
		_ = err.Add("valueF", "must be multiple of 2")
	}
}

func (p ExamplePatterns) ValidateValueFmaybe(err *validation.Errors) {
	if p.ValueFmaybe == nil {
		return
	}

	if *p.ValueFmaybe < 2 {
		_ = err.Add("valueFMaybe", "must be >= 2")
	}

	if *p.ValueFmaybe > 10 {
		_ = err.Add("valueFMaybe", "must be <= 10")
	}

	if math.Mod(float64(*p.ValueFmaybe), 2) != 0 {
		_ = err.Add("valueFMaybe", "must be multiple of 2")
	}
}

func (p ExamplePatterns) ValidateValueMaybe(err *validation.Errors) {
	if p.ValueMaybe == nil {
		return
	}

	if *p.ValueMaybe < 2 {
		_ = err.Add("valueMaybe", "must be >= 2")
	}

	if *p.ValueMaybe > 10 {
		_ = err.Add("valueMaybe", "must be <= 10")
	}

	if *p.ValueMaybe%2 != 0 {
		_ = err.Add("valueMaybe", "must be multiple of 2")
	}
}

func (p ExamplePatterns) ValidateValues(err *validation.Errors) {
	if len(p.Values) < 2 {
		_ = err.Add("values", "length must be >= 2")
	}

	if len(p.Values) > 10 {
		_ = err.Add("values", "length must be <= 10")
	}
}

func (p ExamplePatterns) ValidateValuesMaybe(err *validation.Errors) {
	if p.ValuesMaybe == nil {
		return
	}

	if len(*p.ValuesMaybe) < 2 {
		_ = err.Add("valuesMaybe", "length must be >= 2")
	}

	if len(*p.ValuesMaybe) > 10 {
		_ = err.Add("valuesMaybe", "length must be <= 10")
	}
}

// ExamplePlayerAlways
//
// OpenAPI Component Schema: PlayerAlways
type ExamplePlayerAlways struct {
	ID uuid.UUID `json:"id"`
}

func (p *ExamplePlayerAlways) UnmarshalJSON(b []byte) error {
	var err error
	var requiredCheck map[string]any

	err = json.Unmarshal(b, &requiredCheck)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExamplePlayerAlways.UnmarshalJSON Required: `%v`: %w", string(b), err)}
	}

	var validationErrors validation.Errors

	if _, ok := requiredCheck["id"]; !ok {
		validationErrors.Add("id", ErrExampleMissingRequiredField)
	}

	if validationErrors != nil {
		return validationErrors.GetErr()
	}

	type ExamplePlayerAlwaysJSON ExamplePlayerAlways
	var parseObject ExamplePlayerAlwaysJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExamplePlayerAlways.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExamplePlayerAlways(parseObject)

	*p = v

	return nil
}

// uuid.UUID
//
// OpenAPI Component Schema: PlayerId
type ExamplePlayerID uuid.UUID

// ExamplePlayerMaybe
//
// OpenAPI Component Schema: PlayerMaybe
type ExamplePlayerMaybe struct {
	ID uuid.UUID `json:"id"`
}

func (p *ExamplePlayerMaybe) UnmarshalJSON(b []byte) error {
	var err error
	var requiredCheck map[string]any

	err = json.Unmarshal(b, &requiredCheck)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExamplePlayerMaybe.UnmarshalJSON Required: `%v`: %w", string(b), err)}
	}

	var validationErrors validation.Errors

	if _, ok := requiredCheck["id"]; !ok {
		validationErrors.Add("id", ErrExampleMissingRequiredField)
	}

	if validationErrors != nil {
		return validationErrors.GetErr()
	}

	type ExamplePlayerMaybeJSON ExamplePlayerMaybe
	var parseObject ExamplePlayerMaybeJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExamplePlayerMaybe.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExamplePlayerMaybe(parseObject)

	*p = v

	return nil
}

// ExampleSeason
//
// OpenAPI Component Schema: Season

// ExampleSeason
// Component Schema : Season
type ExampleSeason int8

const (
	UnknownExampleSeason ExampleSeason = iota
	ExampleSeasonSpring
	ExampleSeasonSummer
	ExampleSeasonFall
	ExampleSeasonWinter
)

func NewExampleSeason(name string) ExampleSeason {
	switch name {
	case "spring":
		return ExampleSeasonSpring
	case "summer":
		return ExampleSeasonSummer
	case "fall":
		return ExampleSeasonFall
	case "winter":
		return ExampleSeasonWinter
	}

	return ExampleSeason(0)
}

var ExampleSeasonString = map[ExampleSeason]string{
	ExampleSeasonSpring: "spring",
	ExampleSeasonSummer: "summer",
	ExampleSeasonFall:   "fall",
	ExampleSeasonWinter: "winter",
}

func (e ExampleSeason) String() string {
	return ExampleSeasonString[e]
}

func (e *ExampleSeason) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleSeason(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleSeason(s)

	return nil
}

func (e ExampleSeason) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleSeason) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleSeason) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleSeason.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleSeason(s)

	return nil
}

// ExampleSeasonNullable
//
// OpenAPI Component Schema: SeasonNullable

// ExampleSeasonNullable
// Component Schema : SeasonNullable
type ExampleSeasonNullable int8

const (
	UnknownExampleSeasonNullable ExampleSeasonNullable = iota
	ExampleSeasonNullableSpring
	ExampleSeasonNullableSummer
	ExampleSeasonNullableFall
	ExampleSeasonNullableWinter
)

func NewExampleSeasonNullable(name string) ExampleSeasonNullable {
	switch name {
	case "spring":
		return ExampleSeasonNullableSpring
	case "summer":
		return ExampleSeasonNullableSummer
	case "fall":
		return ExampleSeasonNullableFall
	case "winter":
		return ExampleSeasonNullableWinter
	}

	return ExampleSeasonNullable(0)
}

var ExampleSeasonNullableString = map[ExampleSeasonNullable]string{
	ExampleSeasonNullableSpring: "spring",
	ExampleSeasonNullableSummer: "summer",
	ExampleSeasonNullableFall:   "fall",
	ExampleSeasonNullableWinter: "winter",
}

func (e ExampleSeasonNullable) String() string {
	return ExampleSeasonNullableString[e]
}

func (e *ExampleSeasonNullable) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleSeasonNullable(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleSeasonNullable(s)

	return nil
}

func (e ExampleSeasonNullable) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleSeasonNullable) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleSeasonNullable) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleSeasonNullable.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleSeasonNullable(s)

	return nil
}

// string
//
// OpenAPI Component Schema: State
type ExampleState string

var exampleStatePattern = regexp.MustCompile(`(enabled|disabled)`)

func (p *ExampleState) UnmarshalJSON(b []byte) error {
	var err error

	type ExampleStateJSON ExampleState
	var parseObject ExampleStateJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleState.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleState(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleState) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleState // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleState.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleState) Validate() error {
	var err validation.Errors

	if len(p) < 2 {
		_ = err.Add("", "length must be >= 2")
	}

	if len(p) > 10 {
		_ = err.Add("", "length must be <= 10")
	}

	if p != "" && !exampleStatePattern.MatchString(string(p)) {
		_ = err.Add("", `must match "(enabled|disabled)"`)
	}

	return err.GetErr()
}

// ExampleSubPattern
//
// OpenAPI Component Schema: SubPattern
type ExampleSubPattern struct {
	Num int32 `json:"num,omitempty"`
}

func (p *ExampleSubPattern) UnmarshalJSON(b []byte) error {
	var err error

	type ExampleSubPatternJSON ExampleSubPattern
	var parseObject ExampleSubPatternJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleSubPattern.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleSubPattern(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleSubPattern) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleSubPattern // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleSubPattern.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleSubPattern) Validate() error {
	var err validation.Errors

	p.ValidateNum(&err)

	return err.GetErr()
}

func (p ExampleSubPattern) ValidateNum(err *validation.Errors) {
	if p.Num < 2 {
		_ = err.Add("num", "must be >= 2")
	}
}

// []ExampleXarrayEnum
//
// OpenAPI Component Schema: XArrayEnum
type ExampleXarrayEnum []ExampleXarrayEnumItem

// ExampleXarrayEnumItem
//
// OpenAPI []ExampleXarrayEnum inline item XArrayEnum: XarrayEnumItem

// ExampleXarrayEnumItem
// []ExampleXarrayEnum inline item XArrayEnum : XarrayEnumItem
type ExampleXarrayEnumItem int8

const (
	UnknownExampleXarrayEnumItem ExampleXarrayEnumItem = iota
	ExampleXarrayEnumItemOptionA
	ExampleXarrayEnumItemOptionB
	ExampleXarrayEnumItemOptionC
)

func NewExampleXarrayEnumItem(name string) ExampleXarrayEnumItem {
	switch name {
	case "option_a":
		return ExampleXarrayEnumItemOptionA
	case "option_b":
		return ExampleXarrayEnumItemOptionB
	case "option_c":
		return ExampleXarrayEnumItemOptionC
	}

	return ExampleXarrayEnumItem(0)
}

var ExampleXarrayEnumItemString = map[ExampleXarrayEnumItem]string{
	ExampleXarrayEnumItemOptionA: "option_a",
	ExampleXarrayEnumItemOptionB: "option_b",
	ExampleXarrayEnumItemOptionC: "option_c",
}

func (e ExampleXarrayEnumItem) String() string {
	return ExampleXarrayEnumItemString[e]
}

func (e *ExampleXarrayEnumItem) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleXarrayEnumItem(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleXarrayEnumItem(s)

	return nil
}

func (e ExampleXarrayEnumItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleXarrayEnumItem) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleXarrayEnumItem) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleXarrayEnumItem.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleXarrayEnumItem(s)

	return nil
}

// []ExampleXarrayObjectArrayEnum
//
// OpenAPI Component Schema: XArrayObjectArrayEnum
type ExampleXarrayObjectArrayEnum []ExampleXarrayObjectArrayEnumItem

// ExampleXarrayObjectArrayEnumItem
//
// OpenAPI []ExampleXarrayObjectArrayEnum inline item XArrayObjectArrayEnum: XarrayObjectArrayEnumItem
type ExampleXarrayObjectArrayEnumItem struct {
	List []ExampleXarrayObjectArrayEnumItemList `json:"list,omitempty"`
}

// ExampleXarrayObjectArrayEnumItemList
//
// OpenAPI ExampleXarrayObjectArrayEnumItem inline item list: XarrayObjectArrayEnumItemList

// ExampleXarrayObjectArrayEnumItemList
// ExampleXarrayObjectArrayEnumItem inline item list : XarrayObjectArrayEnumItemList
type ExampleXarrayObjectArrayEnumItemList int8

const (
	UnknownExampleXarrayObjectArrayEnumItemList ExampleXarrayObjectArrayEnumItemList = iota
	ExampleXarrayObjectArrayEnumItemListOptionA
	ExampleXarrayObjectArrayEnumItemListOptionB
	ExampleXarrayObjectArrayEnumItemListOptionC
)

func NewExampleXarrayObjectArrayEnumItemList(name string) ExampleXarrayObjectArrayEnumItemList {
	switch name {
	case "option_a":
		return ExampleXarrayObjectArrayEnumItemListOptionA
	case "option_b":
		return ExampleXarrayObjectArrayEnumItemListOptionB
	case "option_c":
		return ExampleXarrayObjectArrayEnumItemListOptionC
	}

	return ExampleXarrayObjectArrayEnumItemList(0)
}

var ExampleXarrayObjectArrayEnumItemListString = map[ExampleXarrayObjectArrayEnumItemList]string{
	ExampleXarrayObjectArrayEnumItemListOptionA: "option_a",
	ExampleXarrayObjectArrayEnumItemListOptionB: "option_b",
	ExampleXarrayObjectArrayEnumItemListOptionC: "option_c",
}

func (e ExampleXarrayObjectArrayEnumItemList) String() string {
	return ExampleXarrayObjectArrayEnumItemListString[e]
}

func (e *ExampleXarrayObjectArrayEnumItemList) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleXarrayObjectArrayEnumItemList(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleXarrayObjectArrayEnumItemList(s)

	return nil
}

func (e ExampleXarrayObjectArrayEnumItemList) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleXarrayObjectArrayEnumItemList) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleXarrayObjectArrayEnumItemList) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleXarrayObjectArrayEnumItemList.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleXarrayObjectArrayEnumItemList(s)

	return nil
}

// []ExampleXarrayObjectEnum
//
// OpenAPI Component Schema: XArrayObjectEnum
type ExampleXarrayObjectEnum []ExampleXarrayObjectEnumItem

// ExampleXarrayObjectEnumItem
//
// OpenAPI []ExampleXarrayObjectEnum inline item XArrayObjectEnum: XarrayObjectEnumItem
type ExampleXarrayObjectEnumItem struct {
	Options ExampleXarrayObjectEnumItemOptions `json:"options,omitempty,omitzero"`
}

// ExampleXarrayObjectEnumItemOptions
// []ExampleXarrayObjectEnum inline item XArrayObjectEnum : options
type ExampleXarrayObjectEnumItemOptions int8

const (
	UnknownExampleXarrayObjectEnumItemOptions ExampleXarrayObjectEnumItemOptions = iota
	ExampleXarrayObjectEnumItemOptionsOptionA
	ExampleXarrayObjectEnumItemOptionsOptionB
	ExampleXarrayObjectEnumItemOptionsOptionC
)

func NewExampleXarrayObjectEnumItemOptions(name string) ExampleXarrayObjectEnumItemOptions {
	switch name {
	case "option_a":
		return ExampleXarrayObjectEnumItemOptionsOptionA
	case "option_b":
		return ExampleXarrayObjectEnumItemOptionsOptionB
	case "option_c":
		return ExampleXarrayObjectEnumItemOptionsOptionC
	}

	return ExampleXarrayObjectEnumItemOptions(0)
}

var ExampleXarrayObjectEnumItemOptionsString = map[ExampleXarrayObjectEnumItemOptions]string{
	ExampleXarrayObjectEnumItemOptionsOptionA: "option_a",
	ExampleXarrayObjectEnumItemOptionsOptionB: "option_b",
	ExampleXarrayObjectEnumItemOptionsOptionC: "option_c",
}

func (e ExampleXarrayObjectEnumItemOptions) String() string {
	return ExampleXarrayObjectEnumItemOptionsString[e]
}

func (e *ExampleXarrayObjectEnumItemOptions) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleXarrayObjectEnumItemOptions(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleXarrayObjectEnumItemOptions(s)

	return nil
}

func (e ExampleXarrayObjectEnumItemOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleXarrayObjectEnumItemOptions) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleXarrayObjectEnumItemOptions) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleXarrayObjectEnumItemOptions.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleXarrayObjectEnumItemOptions(s)

	return nil
}

// ExampleXobjectArrayEnum
//
// OpenAPI Component Schema: XObjectArrayEnum
type ExampleXobjectArrayEnum struct {
	Items []ExampleXobjectArrayEnumItems `json:"items,omitempty"`
}

// ExampleXobjectArrayEnumItems
//
// OpenAPI ExampleXobjectArrayEnum inline item items: XobjectArrayEnumItems

// ExampleXobjectArrayEnumItems
// ExampleXobjectArrayEnum inline item items : XobjectArrayEnumItems
type ExampleXobjectArrayEnumItems int8

const (
	UnknownExampleXobjectArrayEnumItems ExampleXobjectArrayEnumItems = iota
	ExampleXobjectArrayEnumItemsOptionA
	ExampleXobjectArrayEnumItemsOptionB
	ExampleXobjectArrayEnumItemsOptionC
)

func NewExampleXobjectArrayEnumItems(name string) ExampleXobjectArrayEnumItems {
	switch name {
	case "option_a":
		return ExampleXobjectArrayEnumItemsOptionA
	case "option_b":
		return ExampleXobjectArrayEnumItemsOptionB
	case "option_c":
		return ExampleXobjectArrayEnumItemsOptionC
	}

	return ExampleXobjectArrayEnumItems(0)
}

var ExampleXobjectArrayEnumItemsString = map[ExampleXobjectArrayEnumItems]string{
	ExampleXobjectArrayEnumItemsOptionA: "option_a",
	ExampleXobjectArrayEnumItemsOptionB: "option_b",
	ExampleXobjectArrayEnumItemsOptionC: "option_c",
}

func (e ExampleXobjectArrayEnumItems) String() string {
	return ExampleXobjectArrayEnumItemsString[e]
}

func (e *ExampleXobjectArrayEnumItems) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleXobjectArrayEnumItems(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleXobjectArrayEnumItems(s)

	return nil
}

func (e ExampleXobjectArrayEnumItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleXobjectArrayEnumItems) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleXobjectArrayEnumItems) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleXobjectArrayEnumItems.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleXobjectArrayEnumItems(s)

	return nil
}

// ExampleXobjectArrayObjectEnum
//
// OpenAPI Component Schema: XObjectArrayObjectEnum
type ExampleXobjectArrayObjectEnum struct {
	List []ExampleXobjectArrayObjectEnumList `json:"list,omitempty"`
}

// ExampleXobjectArrayObjectEnumList
//
// OpenAPI ExampleXobjectArrayObjectEnum inline item list: XobjectArrayObjectEnumList
type ExampleXobjectArrayObjectEnumList struct {
	Options ExampleXobjectArrayObjectEnumListOptions `json:"options,omitempty,omitzero"`
}

// ExampleXobjectArrayObjectEnumListOptions
// ExampleXobjectArrayObjectEnum inline item list : options
type ExampleXobjectArrayObjectEnumListOptions int8

const (
	UnknownExampleXobjectArrayObjectEnumListOptions ExampleXobjectArrayObjectEnumListOptions = iota
	ExampleXobjectArrayObjectEnumListOptionsOptionA
	ExampleXobjectArrayObjectEnumListOptionsOptionB
	ExampleXobjectArrayObjectEnumListOptionsOptionC
)

func NewExampleXobjectArrayObjectEnumListOptions(name string) ExampleXobjectArrayObjectEnumListOptions {
	switch name {
	case "option_a":
		return ExampleXobjectArrayObjectEnumListOptionsOptionA
	case "option_b":
		return ExampleXobjectArrayObjectEnumListOptionsOptionB
	case "option_c":
		return ExampleXobjectArrayObjectEnumListOptionsOptionC
	}

	return ExampleXobjectArrayObjectEnumListOptions(0)
}

var ExampleXobjectArrayObjectEnumListOptionsString = map[ExampleXobjectArrayObjectEnumListOptions]string{
	ExampleXobjectArrayObjectEnumListOptionsOptionA: "option_a",
	ExampleXobjectArrayObjectEnumListOptionsOptionB: "option_b",
	ExampleXobjectArrayObjectEnumListOptionsOptionC: "option_c",
}

func (e ExampleXobjectArrayObjectEnumListOptions) String() string {
	return ExampleXobjectArrayObjectEnumListOptionsString[e]
}

func (e *ExampleXobjectArrayObjectEnumListOptions) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleXobjectArrayObjectEnumListOptions(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleXobjectArrayObjectEnumListOptions(s)

	return nil
}

func (e ExampleXobjectArrayObjectEnumListOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleXobjectArrayObjectEnumListOptions) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleXobjectArrayObjectEnumListOptions) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleXobjectArrayObjectEnumListOptions.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleXobjectArrayObjectEnumListOptions(s)

	return nil
}

// ExampleXobjectEnum
//
// OpenAPI Component Schema: XObjectEnum
type ExampleXobjectEnum struct {
	Options ExampleXobjectEnumOptions `json:"options,omitempty,omitzero"`
}

// ExampleXobjectEnumOptions
// Component Schema : options
type ExampleXobjectEnumOptions int8

const (
	UnknownExampleXobjectEnumOptions ExampleXobjectEnumOptions = iota
	ExampleXobjectEnumOptionsOptionA
	ExampleXobjectEnumOptionsOptionB
	ExampleXobjectEnumOptionsOptionC
)

func NewExampleXobjectEnumOptions(name string) ExampleXobjectEnumOptions {
	switch name {
	case "option_a":
		return ExampleXobjectEnumOptionsOptionA
	case "option_b":
		return ExampleXobjectEnumOptionsOptionB
	case "option_c":
		return ExampleXobjectEnumOptionsOptionC
	}

	return ExampleXobjectEnumOptions(0)
}

var ExampleXobjectEnumOptionsString = map[ExampleXobjectEnumOptions]string{
	ExampleXobjectEnumOptionsOptionA: "option_a",
	ExampleXobjectEnumOptionsOptionB: "option_b",
	ExampleXobjectEnumOptionsOptionC: "option_c",
}

func (e ExampleXobjectEnumOptions) String() string {
	return ExampleXobjectEnumOptionsString[e]
}

func (e *ExampleXobjectEnumOptions) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleXobjectEnumOptions(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleXobjectEnumOptions(s)

	return nil
}

func (e ExampleXobjectEnumOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleXobjectEnumOptions) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleXobjectEnumOptions) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleXobjectEnumOptions.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleXobjectEnumOptions(s)

	return nil
}

// ExampleErrorV1
// Standard error format
//
// OpenAPI Component Schema: errorV1
type ExampleErrorV1 struct {
	Code    string `json:"code,omitempty,omitzero"`
	Message string `json:"message,omitempty,omitzero"`
}

// ExampleExampleKebabCaseField
//
// OpenAPI Component Schema: example-kebab-case-field
type ExampleExampleKebabCaseField struct {
	Seniority string `json:"seniority,omitempty,omitzero"`
	Tier      string `json:"tier,omitempty,omitzero"`
}

var (
	exampleExampleKebabCaseFieldSeniorityPattern = regexp.MustCompile(`(^[1-9]\d*$)`)
	exampleExampleKebabCaseFieldTierPattern      = regexp.MustCompile(`(alpha|beta|gama)`)
)

func (p *ExampleExampleKebabCaseField) UnmarshalJSON(b []byte) error {
	var err error

	type ExampleExampleKebabCaseFieldJSON ExampleExampleKebabCaseField
	var parseObject ExampleExampleKebabCaseFieldJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleExampleKebabCaseField.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleExampleKebabCaseField(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleExampleKebabCaseField) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleExampleKebabCaseField // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleExampleKebabCaseField.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleExampleKebabCaseField) Validate() error {
	var err validation.Errors

	p.ValidateSeniority(&err)
	p.ValidateTier(&err)

	return err.GetErr()
}

func (p ExampleExampleKebabCaseField) ValidateSeniority(err *validation.Errors) {
	if p.Seniority != "" && !exampleExampleKebabCaseFieldSeniorityPattern.MatchString(string(p.Seniority)) {
		_ = err.Add("seniority", `must match "(^[1-9]\d*$)"`)
	}
}

func (p ExampleExampleKebabCaseField) ValidateTier(err *validation.Errors) {
	if p.Tier != "" && !exampleExampleKebabCaseFieldTierPattern.MatchString(string(p.Tier)) {
		_ = err.Add("tier", `must match "(alpha|beta|gama)"`)
	}
}

// Component Parameters

// ExampleColorQuery
// Component Parameter: color
type ExampleColorQuery int8

const (
	UnknownExampleColorQuery ExampleColorQuery = iota
	ExampleColorQueryRed
	ExampleColorQueryGreen
	ExampleColorQueryBlue
)

func NewExampleColorQuery(name string) ExampleColorQuery {
	switch name {
	case "red":
		return ExampleColorQueryRed
	case "green":
		return ExampleColorQueryGreen
	case "blue":
		return ExampleColorQueryBlue
	}

	return ExampleColorQuery(0)
}

var ExampleColorQueryString = map[ExampleColorQuery]string{
	ExampleColorQueryRed:   "red",
	ExampleColorQueryGreen: "green",
	ExampleColorQueryBlue:  "blue",
}

func (e ExampleColorQuery) String() string {
	return ExampleColorQueryString[e]
}

func (e *ExampleColorQuery) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleColorQuery(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleColorQuery(s)

	return nil
}

func (e ExampleColorQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleColorQuery) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleColorQuery) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleColorQuery.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleColorQuery(s)

	return nil
}

// ExampleColorQueryDefault
// Component Parameter: colorDefault
type ExampleColorQueryDefault int8

const (
	UnknownExampleColorQueryDefault ExampleColorQueryDefault = iota
	ExampleColorQueryDefaultRed
	ExampleColorQueryDefaultGreen
	ExampleColorQueryDefaultBlue
)

func NewExampleColorQueryDefault(name string) ExampleColorQueryDefault {
	switch name {
	case "red":
		return ExampleColorQueryDefaultRed
	case "green":
		return ExampleColorQueryDefaultGreen
	case "blue":
		return ExampleColorQueryDefaultBlue
	}

	return ExampleColorQueryDefault(0)
}

var ExampleColorQueryDefaultString = map[ExampleColorQueryDefault]string{
	ExampleColorQueryDefaultRed:   "red",
	ExampleColorQueryDefaultGreen: "green",
	ExampleColorQueryDefaultBlue:  "blue",
}

func (e ExampleColorQueryDefault) String() string {
	return ExampleColorQueryDefaultString[e]
}

func (e *ExampleColorQueryDefault) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleColorQueryDefault(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleColorQueryDefault(s)

	return nil
}

func (e ExampleColorQueryDefault) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleColorQueryDefault) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleColorQueryDefault) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleColorQueryDefault.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleColorQueryDefault(s)

	return nil
}

// Path Operations

// ExampleAddFormRequest
//
// OpenAPI AddForm Body: AddForm Request
type ExampleAddFormRequest struct {
	F01      bool                          `json:"f01,omitempty"`
	F01Null  *bool                         `json:"f01Null,omitempty"`
	F01B     bool                          `json:"f01b,omitempty"`
	F01BNull *bool                         `json:"f01bNull,omitempty"`
	F02      int32                         `json:"f02,omitempty"`
	F02Null  *int32                        `json:"f02Null,omitempty"`
	F03      int32                         `json:"f03,omitempty"`
	F03Null  *int32                        `json:"f03Null,omitempty"`
	F04      int64                         `json:"f04,omitempty"`
	F04Null  *int64                        `json:"f04Null,omitempty"`
	F05      time.Time                     `json:"f05,omitempty,omitzero"`
	F05Null  *time.Time                    `json:"f05Null,omitempty,omitzero"`
	F06      uuid.UUID                     `json:"f06,omitempty,omitzero"`
	F06Null  *uuid.UUID                    `json:"f06Null,omitempty,omitzero"`
	F07      string                        `json:"f07"`
	F07Null  *string                       `json:"f07Null,omitempty,omitzero"`
	F08      ExampleAddFormRequestF08      `json:"f08,omitempty,omitzero"`
	F08Null  *ExampleAddFormRequestF08Null `json:"f08Null,omitempty,omitzero"`
	F09      ExampleSeason                 `json:"f09,omitempty,omitzero"`
	F09Null  *ExampleSeasonNullable        `json:"f09Null,omitempty,omitzero"`
	F10      []string                      `json:"f10,omitempty"`
	F11      []int32                       `json:"f11,omitempty"`
	F12      []ExampleSeason               `json:"f12,omitempty"`
	F13      string                        `json:"f13,omitempty,omitzero"`
	F13Null  *string                       `json:"f13Null,omitempty,omitzero"`
}

// ExampleAddFormRequestF08
// AddForm Body : f08
type ExampleAddFormRequestF08 int8

const (
	UnknownExampleAddFormRequestF08 ExampleAddFormRequestF08 = iota
	ExampleAddFormRequestF08ValueA
	ExampleAddFormRequestF08ValueB
	ExampleAddFormRequestF08ValueC
)

func NewExampleAddFormRequestF08(name string) ExampleAddFormRequestF08 {
	switch name {
	case "valueA":
		return ExampleAddFormRequestF08ValueA
	case "valueB":
		return ExampleAddFormRequestF08ValueB
	case "valueC":
		return ExampleAddFormRequestF08ValueC
	}

	return ExampleAddFormRequestF08(0)
}

var ExampleAddFormRequestF08String = map[ExampleAddFormRequestF08]string{
	ExampleAddFormRequestF08ValueA: "valueA",
	ExampleAddFormRequestF08ValueB: "valueB",
	ExampleAddFormRequestF08ValueC: "valueC",
}

func (e ExampleAddFormRequestF08) String() string {
	return ExampleAddFormRequestF08String[e]
}

func (e *ExampleAddFormRequestF08) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleAddFormRequestF08(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleAddFormRequestF08(s)

	return nil
}

func (e ExampleAddFormRequestF08) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleAddFormRequestF08) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleAddFormRequestF08) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleAddFormRequestF08.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleAddFormRequestF08(s)

	return nil
}

// ExampleAddFormRequestF08Null
// AddForm Body : f08Null
type ExampleAddFormRequestF08Null int8

const (
	UnknownExampleAddFormRequestF08Null ExampleAddFormRequestF08Null = iota
	ExampleAddFormRequestF08NullValueA
	ExampleAddFormRequestF08NullValueB
	ExampleAddFormRequestF08NullValueC
)

func NewExampleAddFormRequestF08Null(name string) ExampleAddFormRequestF08Null {
	switch name {
	case "valueA":
		return ExampleAddFormRequestF08NullValueA
	case "valueB":
		return ExampleAddFormRequestF08NullValueB
	case "valueC":
		return ExampleAddFormRequestF08NullValueC
	}

	return ExampleAddFormRequestF08Null(0)
}

var ExampleAddFormRequestF08NullString = map[ExampleAddFormRequestF08Null]string{
	ExampleAddFormRequestF08NullValueA: "valueA",
	ExampleAddFormRequestF08NullValueB: "valueB",
	ExampleAddFormRequestF08NullValueC: "valueC",
}

func (e ExampleAddFormRequestF08Null) String() string {
	return ExampleAddFormRequestF08NullString[e]
}

func (e *ExampleAddFormRequestF08Null) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleAddFormRequestF08Null(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleAddFormRequestF08Null(s)

	return nil
}

func (e ExampleAddFormRequestF08Null) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleAddFormRequestF08Null) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleAddFormRequestF08Null) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleAddFormRequestF08Null.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleAddFormRequestF08Null(s)

	return nil
}

func ParseFormExampleAddFormRequest(r *http.Request) (ExampleAddFormRequest, error) {
	var (
		parseErrors validation.Errors
		err         error
		v           ExampleAddFormRequest
	)

	paramF01, ok, err := forms.GetBool(r.FormValue, "f01", false)
	if err != nil {
		parseErrors.Add("f01", err)
	} else if ok {
		v.F01 = paramF01
	}

	paramF01Null, ok, err := forms.GetBool(r.FormValue, "f01Null", false)
	if err != nil {
		parseErrors.Add("f01Null", err)
	} else if ok {
		v.F01Null = &paramF01Null
	}

	paramF01B, ok, err := forms.GetBool(r.FormValue, "f01b", false)
	if err != nil {
		parseErrors.Add("f01b", err)
	} else if !ok {
		paramF01B = true
	}

	v.F01B = paramF01B

	paramF01BNull, ok, err := forms.GetBool(r.FormValue, "f01bNull", false)
	if err != nil {
		parseErrors.Add("f01bNull", err)
	} else if !ok {
		paramF01BNull = true
	}

	v.F01BNull = &paramF01BNull

	paramF02, ok, err := forms.GetInt32(r.FormValue, "f02", false)
	if err != nil {
		parseErrors.Add("f02", err)
	} else if ok {
		v.F02 = paramF02
	}

	paramF02Null, ok, err := forms.GetInt32(r.FormValue, "f02Null", false)
	if err != nil {
		parseErrors.Add("f02Null", err)
	} else if ok {
		v.F02Null = &paramF02Null
	}

	paramF03, ok, err := forms.GetInt32(r.FormValue, "f03", false)
	if err != nil {
		parseErrors.Add("f03", err)
	} else if ok {
		v.F03 = paramF03
	}

	paramF03Null, ok, err := forms.GetInt32(r.FormValue, "f03Null", false)
	if err != nil {
		parseErrors.Add("f03Null", err)
	} else if ok {
		v.F03Null = &paramF03Null
	}

	paramF04, ok, err := forms.GetInt64(r.FormValue, "f04", false)
	if err != nil {
		parseErrors.Add("f04", err)
	} else if !ok {
		paramF04 = 1
	}

	v.F04 = paramF04

	paramF04Null, ok, err := forms.GetInt64(r.FormValue, "f04Null", false)
	if err != nil {
		parseErrors.Add("f04Null", err)
	} else if !ok {
		paramF04Null = 2
	}

	v.F04Null = &paramF04Null

	paramF05, ok, err := forms.GetTime(r.FormValue, "f05", false)
	if err != nil {
		parseErrors.Add("f05", err)
	} else if ok {
		v.F05 = paramF05
	}

	paramF05Null, ok, err := forms.GetTime(r.FormValue, "f05Null", false)
	if err != nil {
		parseErrors.Add("f05Null", err)
	} else if ok {
		v.F05Null = &paramF05Null
	}

	paramF06, ok, err := forms.GetUUID(r.FormValue, "f06", false)
	if err != nil {
		parseErrors.Add("f06", err)
	} else if ok {
		v.F06 = paramF06
	}

	paramF06Null, ok, err := forms.GetUUID(r.FormValue, "f06Null", false)
	if err != nil {
		parseErrors.Add("f06Null", err)
	} else if ok {
		v.F06Null = &paramF06Null
	}

	paramF07, ok, err := forms.GetString(r.FormValue, "f07", true)
	if err != nil {
		parseErrors.Add("f07", err)
	} else if ok {
		v.F07 = paramF07
	}

	paramF07Null, ok, err := forms.GetString(r.FormValue, "f07Null", false)
	if err != nil {
		parseErrors.Add("f07Null", err)
	} else if ok {
		v.F07Null = &paramF07Null
	}

	paramF08, ok, err := forms.GetEnum(r.FormValue, "f08", false, NewExampleAddFormRequestF08)
	if err != nil {
		parseErrors.Add("f08", err)
	} else if !ok {
		paramF08 = ExampleAddFormRequestF08ValueA
	}

	v.F08 = paramF08

	paramF08Null, ok, err := forms.GetEnum(r.FormValue, "f08Null", false, NewExampleAddFormRequestF08Null)
	if err != nil {
		parseErrors.Add("f08Null", err)
	} else if !ok {
		paramF08Null = ExampleAddFormRequestF08NullValueB
	}

	v.F08Null = &paramF08Null

	paramF09, ok, err := forms.GetEnum(r.FormValue, "f09", false, NewExampleSeason)
	if err != nil {
		parseErrors.Add("f09", err)
	} else if ok {
		v.F09 = paramF09
	}

	paramF09Null, ok, err := forms.GetEnum(r.FormValue, "f09Null", false, NewExampleSeasonNullable)
	if err != nil {
		parseErrors.Add("f09Null", err)
	} else if ok {
		v.F09Null = &paramF09Null
	}

	v.F10, _, err = forms.GetStringArray(r.FormValue, "f10", false)
	if err != nil {
		parseErrors.Add("f10", err)
	}

	v.F11, _, err = forms.GetInt32Array(r.FormValue, "f11", false)
	if err != nil {
		parseErrors.Add("f11", err)
	}

	v.F12, _, err = forms.GetEnumArray(r.FormValue, "f12", false, NewExampleSeason)
	if err != nil {
		parseErrors.Add("f12", err)
	}

	paramF13, ok, err := forms.GetString(r.FormValue, "f13", false)
	if err != nil {
		parseErrors.Add("f13", err)
	} else if !ok {
		paramF13 = "someValue"
	}

	v.F13 = paramF13

	paramF13Null, ok, err := forms.GetString(r.FormValue, "f13Null", false)
	if err != nil {
		parseErrors.Add("f13Null", err)
	} else if !ok {
		paramF13Null = "someValue2"
	}

	v.F13Null = &paramF13Null

	if parseErrors != nil {
		return ExampleAddFormRequest{}, parseErrors.GetErr()
	}

	err = v.Validate()
	if err != nil {
		return ExampleAddFormRequest{}, err
	}

	return v, nil
}

func (p ExampleAddFormRequest) Validate() error {
	var err validation.Errors

	p.ValidateF10(&err)

	return err.GetErr()
}

func (p ExampleAddFormRequest) ValidateF10(err *validation.Errors) {
	if len(p.F10) < 1 {
		_ = err.Add("f10", "length must be >= 1")
	}
}

// ExampleAddMultipartFormRequest
//
// OpenAPI AddMultipartForm Body: AddMultipartForm Request
type ExampleAddMultipartFormRequest struct {
	F1    bool       `json:"f1,omitempty"`
	F2    int32      `json:"f2,omitempty"`
	F3    int32      `json:"f3,omitempty"`
	F4    int64      `json:"f4,omitempty"`
	F5    time.Time  `json:"f5,omitempty,omitzero"`
	F6    uuid.UUID  `json:"f6,omitempty,omitzero"`
	F7    string     `json:"f7,omitempty,omitzero"`
	File1 forms.File `json:"file1"`
	File2 forms.File `json:"file2,omitempty,omitzero"`
}

func ParseFormExampleAddMultipartFormRequest(r *http.Request) (ExampleAddMultipartFormRequest, error) {
	var (
		parseErrors validation.Errors
		err         error
		v           ExampleAddMultipartFormRequest
	)

	paramF1, ok, err := forms.GetBool(r.FormValue, "f1", false)
	if err != nil {
		parseErrors.Add("f1", err)
	} else if ok {
		v.F1 = paramF1
	}

	paramF2, ok, err := forms.GetInt32(r.FormValue, "f2", false)
	if err != nil {
		parseErrors.Add("f2", err)
	} else if ok {
		v.F2 = paramF2
	}

	paramF3, ok, err := forms.GetInt32(r.FormValue, "f3", false)
	if err != nil {
		parseErrors.Add("f3", err)
	} else if ok {
		v.F3 = paramF3
	}

	paramF4, ok, err := forms.GetInt64(r.FormValue, "f4", false)
	if err != nil {
		parseErrors.Add("f4", err)
	} else if ok {
		v.F4 = paramF4
	}

	paramF5, ok, err := forms.GetTime(r.FormValue, "f5", false)
	if err != nil {
		parseErrors.Add("f5", err)
	} else if ok {
		v.F5 = paramF5
	}

	paramF6, ok, err := forms.GetUUID(r.FormValue, "f6", false)
	if err != nil {
		parseErrors.Add("f6", err)
	} else if ok {
		v.F6 = paramF6
	}

	paramF7, ok, err := forms.GetString(r.FormValue, "f7", false)
	if err != nil {
		parseErrors.Add("f7", err)
	} else if ok {
		v.F7 = paramF7
	}

	paramFile1, ok, err := forms.GetFile(r, "file1", true)
	if err != nil {
		parseErrors.Add("file1", err)
	} else if ok {
		v.File1 = paramFile1
	}

	paramFile2, ok, err := forms.GetFile(r, "file2", false)
	if err != nil {
		parseErrors.Add("file2", err)
	} else if ok {
		v.File2 = paramFile2
	}

	if parseErrors != nil {
		return ExampleAddMultipartFormRequest{}, parseErrors.GetErr()
	}

	return v, nil
}

// ExampleAddInlinedAllOfRequest
//
// OpenAPI AddInlinedAllOf Body: AddInlinedAllOf Request
type ExampleAddInlinedAllOfRequest struct {
	Foos    ExampleFooString `json:"foos,omitempty,omitzero"`
	Special bool             `json:"special,omitempty"`
}

func (p *ExampleAddInlinedAllOfRequest) UnmarshalJSON(b []byte) error {
	var err error

	type ExampleAddInlinedAllOfRequestJSON ExampleAddInlinedAllOfRequest
	var parseObject ExampleAddInlinedAllOfRequestJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleAddInlinedAllOfRequest.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleAddInlinedAllOfRequest(parseObject)

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleAddInlinedAllOfRequest) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleAddInlinedAllOfRequest // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleAddInlinedAllOfRequest.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleAddInlinedAllOfRequest) Validate() error {
	var err validation.Errors

	p.ValidateFoos(&err)

	return err.GetErr()
}

func (p ExampleAddInlinedAllOfRequest) ValidateFoos(err *validation.Errors) {
	if subErr := p.Foos.Validate(); subErr != nil {
		_ = err.Add("foos", subErr)
	}
}

// ExampleAddInlinedBodyRequest
//
// OpenAPI AddInlinedBody Body: AddInlinedBody Request
type ExampleAddInlinedBodyRequest struct {
	F01      bool                                 `json:"f01,omitempty"`
	F01Null  *bool                                `json:"f01Null,omitempty"`
	F01B     bool                                 `json:"f01b,omitempty"`
	F01BNull *bool                                `json:"f01bNull,omitempty"`
	F02      int32                                `json:"f02,omitempty"`
	F02Null  *int32                               `json:"f02Null,omitempty"`
	F03      int32                                `json:"f03,omitempty"`
	F03Null  *int32                               `json:"f03Null,omitempty"`
	F04      int64                                `json:"f04,omitempty"`
	F04Null  *int64                               `json:"f04Null,omitempty"`
	F05      time.Time                            `json:"f05,omitempty,omitzero"`
	F05Null  *time.Time                           `json:"f05Null,omitempty,omitzero"`
	F06      uuid.UUID                            `json:"f06,omitempty,omitzero"`
	F06Null  *uuid.UUID                           `json:"f06Null,omitempty,omitzero"`
	F07      string                               `json:"f07"`
	F07Null  *string                              `json:"f07Null,omitempty,omitzero"`
	F08      ExampleAddInlinedBodyRequestF08      `json:"f08,omitempty,omitzero"`
	F08Null  *ExampleAddInlinedBodyRequestF08Null `json:"f08Null,omitempty,omitzero"`
	F09      ExampleSeason                        `json:"f09,omitempty,omitzero"`
	F09Null  *ExampleSeasonNullable               `json:"f09Null,omitempty,omitzero"`
	F10      []string                             `json:"f10"`
	F11      []int32                              `json:"f11,omitempty"`
	F12      []ExampleSeason                      `json:"f12,omitempty"`
	F13      string                               `json:"f13,omitempty,omitzero"`
	F13Null  *string                              `json:"f13Null,omitempty,omitzero"`
}

// ExampleAddInlinedBodyRequestF08
// AddInlinedBody Body : f08
type ExampleAddInlinedBodyRequestF08 int8

const (
	UnknownExampleAddInlinedBodyRequestF08 ExampleAddInlinedBodyRequestF08 = iota
	ExampleAddInlinedBodyRequestF08ValueA
	ExampleAddInlinedBodyRequestF08ValueB
	ExampleAddInlinedBodyRequestF08ValueC
)

func NewExampleAddInlinedBodyRequestF08(name string) ExampleAddInlinedBodyRequestF08 {
	switch name {
	case "valueA":
		return ExampleAddInlinedBodyRequestF08ValueA
	case "valueB":
		return ExampleAddInlinedBodyRequestF08ValueB
	case "valueC":
		return ExampleAddInlinedBodyRequestF08ValueC
	}

	return ExampleAddInlinedBodyRequestF08(0)
}

var ExampleAddInlinedBodyRequestF08String = map[ExampleAddInlinedBodyRequestF08]string{
	ExampleAddInlinedBodyRequestF08ValueA: "valueA",
	ExampleAddInlinedBodyRequestF08ValueB: "valueB",
	ExampleAddInlinedBodyRequestF08ValueC: "valueC",
}

func (e ExampleAddInlinedBodyRequestF08) String() string {
	return ExampleAddInlinedBodyRequestF08String[e]
}

func (e *ExampleAddInlinedBodyRequestF08) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleAddInlinedBodyRequestF08(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleAddInlinedBodyRequestF08(s)

	return nil
}

func (e ExampleAddInlinedBodyRequestF08) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleAddInlinedBodyRequestF08) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleAddInlinedBodyRequestF08) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleAddInlinedBodyRequestF08.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleAddInlinedBodyRequestF08(s)

	return nil
}

// ExampleAddInlinedBodyRequestF08Null
// AddInlinedBody Body : f08Null
type ExampleAddInlinedBodyRequestF08Null int8

const (
	UnknownExampleAddInlinedBodyRequestF08Null ExampleAddInlinedBodyRequestF08Null = iota
	ExampleAddInlinedBodyRequestF08NullValueA
	ExampleAddInlinedBodyRequestF08NullValueB
	ExampleAddInlinedBodyRequestF08NullValueC
)

func NewExampleAddInlinedBodyRequestF08Null(name string) ExampleAddInlinedBodyRequestF08Null {
	switch name {
	case "valueA":
		return ExampleAddInlinedBodyRequestF08NullValueA
	case "valueB":
		return ExampleAddInlinedBodyRequestF08NullValueB
	case "valueC":
		return ExampleAddInlinedBodyRequestF08NullValueC
	}

	return ExampleAddInlinedBodyRequestF08Null(0)
}

var ExampleAddInlinedBodyRequestF08NullString = map[ExampleAddInlinedBodyRequestF08Null]string{
	ExampleAddInlinedBodyRequestF08NullValueA: "valueA",
	ExampleAddInlinedBodyRequestF08NullValueB: "valueB",
	ExampleAddInlinedBodyRequestF08NullValueC: "valueC",
}

func (e ExampleAddInlinedBodyRequestF08Null) String() string {
	return ExampleAddInlinedBodyRequestF08NullString[e]
}

func (e *ExampleAddInlinedBodyRequestF08Null) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleAddInlinedBodyRequestF08Null(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleAddInlinedBodyRequestF08Null(s)

	return nil
}

func (e ExampleAddInlinedBodyRequestF08Null) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleAddInlinedBodyRequestF08Null) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleAddInlinedBodyRequestF08Null) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleAddInlinedBodyRequestF08Null.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleAddInlinedBodyRequestF08Null(s)

	return nil
}

func (p *ExampleAddInlinedBodyRequest) UnmarshalJSON(b []byte) error {
	var err error
	var requiredCheck map[string]any

	err = json.Unmarshal(b, &requiredCheck)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleAddInlinedBodyRequest.UnmarshalJSON Required: `%v`: %w", string(b), err)}
	}

	var validationErrors validation.Errors

	if _, ok := requiredCheck["f07"]; !ok {
		validationErrors.Add("f07", ErrExampleMissingRequiredField)
	}

	if _, ok := requiredCheck["f10"]; !ok {
		validationErrors.Add("f10", ErrExampleMissingRequiredField)
	}

	if validationErrors != nil {
		return validationErrors.GetErr()
	}

	type ExampleAddInlinedBodyRequestJSON ExampleAddInlinedBodyRequest
	var parseObject ExampleAddInlinedBodyRequestJSON

	err = json.Unmarshal(b, &parseObject)
	if err != nil {
		return validation.Error{err.Error(), fmt.Errorf("ExampleAddInlinedBodyRequest.UnmarshalJSON: `%v`: %w", string(b), err)}
	}

	v := ExampleAddInlinedBodyRequest(parseObject)

	if _, ok := requiredCheck["f01b"]; !ok {
		v.F01B = true
	}

	if _, ok := requiredCheck["f01bNull"]; !ok {
		var defaultVal bool = true
		v.F01BNull = &defaultVal
	}

	if _, ok := requiredCheck["f04"]; !ok {
		v.F04 = 1
	}

	if _, ok := requiredCheck["f04Null"]; !ok {
		var defaultVal int64 = 2
		v.F04Null = &defaultVal
	}

	if _, ok := requiredCheck["f08"]; !ok {
		v.F08 = ExampleAddInlinedBodyRequestF08ValueA
	}

	if _, ok := requiredCheck["f08Null"]; !ok {
		defaultVal := ExampleAddInlinedBodyRequestF08NullValueB
		v.F08Null = &defaultVal
	}

	if _, ok := requiredCheck["f13"]; !ok {
		v.F13 = "someValue"
	}

	if _, ok := requiredCheck["f13Null"]; !ok {
		var defaultVal string = "someValue2"
		v.F13Null = &defaultVal
	}

	err = v.Validate()
	if err != nil {
		return err
	}

	*p = v

	return nil
}

func (p ExampleAddInlinedBodyRequest) MarshalJSON() ([]byte, error) {
	err := p.Validate()
	if err != nil {
		return nil, err
	}

	type unvalidated ExampleAddInlinedBodyRequest // Skips the validation check
	b, err := json.Marshal(unvalidated(p))
	if err != nil {
		return nil, fmt.Errorf("ExampleAddInlinedBodyRequest.Marshal: `%+v`: %w", p, err)
	}

	return b, nil
}

func (p ExampleAddInlinedBodyRequest) Validate() error {
	var err validation.Errors

	p.ValidateF10(&err)

	return err.GetErr()
}

func (p ExampleAddInlinedBodyRequest) ValidateF10(err *validation.Errors) {
	if len(p.F10) < 1 {
		_ = err.Add("f10", "length must be >= 1")
	}
}

// ExampleGetExampleParamsEnumTest
// Enum Description
// Op: getExampleParams Param: enumTest
type ExampleGetExampleParamsEnumTest int8

const (
	UnknownExampleGetExampleParamsEnumTest ExampleGetExampleParamsEnumTest = iota
	ExampleGetExampleParamsEnumTestValueA
	ExampleGetExampleParamsEnumTestValueB
)

func NewExampleGetExampleParamsEnumTest(name string) ExampleGetExampleParamsEnumTest {
	switch name {
	case "valueA":
		return ExampleGetExampleParamsEnumTestValueA
	case "valueB":
		return ExampleGetExampleParamsEnumTestValueB
	}

	return ExampleGetExampleParamsEnumTest(0)
}

var ExampleGetExampleParamsEnumTestString = map[ExampleGetExampleParamsEnumTest]string{
	ExampleGetExampleParamsEnumTestValueA: "valueA",
	ExampleGetExampleParamsEnumTestValueB: "valueB",
}

func (e ExampleGetExampleParamsEnumTest) String() string {
	return ExampleGetExampleParamsEnumTestString[e]
}

func (e *ExampleGetExampleParamsEnumTest) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleGetExampleParamsEnumTest(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleGetExampleParamsEnumTest(s)

	return nil
}

func (e ExampleGetExampleParamsEnumTest) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleGetExampleParamsEnumTest) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleGetExampleParamsEnumTest) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleGetExampleParamsEnumTest.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleGetExampleParamsEnumTest(s)

	return nil
}

// ExampleGetRawRequestVehicle
// Op: getRawRequest Param: vehicle
type ExampleGetRawRequestVehicle int8

const (
	UnknownExampleGetRawRequestVehicle ExampleGetRawRequestVehicle = iota
	ExampleGetRawRequestVehicleCar
	ExampleGetRawRequestVehicleTruck
	ExampleGetRawRequestVehicleBike
)

func NewExampleGetRawRequestVehicle(name string) ExampleGetRawRequestVehicle {
	switch name {
	case "car":
		return ExampleGetRawRequestVehicleCar
	case "truck":
		return ExampleGetRawRequestVehicleTruck
	case "bike":
		return ExampleGetRawRequestVehicleBike
	}

	return ExampleGetRawRequestVehicle(0)
}

var ExampleGetRawRequestVehicleString = map[ExampleGetRawRequestVehicle]string{
	ExampleGetRawRequestVehicleCar:   "car",
	ExampleGetRawRequestVehicleTruck: "truck",
	ExampleGetRawRequestVehicleBike:  "bike",
}

func (e ExampleGetRawRequestVehicle) String() string {
	return ExampleGetRawRequestVehicleString[e]
}

func (e *ExampleGetRawRequestVehicle) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleGetRawRequestVehicle(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleGetRawRequestVehicle(s)

	return nil
}

func (e ExampleGetRawRequestVehicle) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleGetRawRequestVehicle) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleGetRawRequestVehicle) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleGetRawRequestVehicle.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleGetRawRequestVehicle(s)

	return nil
}

// ExampleGetRawRequestResponseVehicle
// Op: getRawRequestResponse Param: vehicle
type ExampleGetRawRequestResponseVehicle int8

const (
	UnknownExampleGetRawRequestResponseVehicle ExampleGetRawRequestResponseVehicle = iota
	ExampleGetRawRequestResponseVehicleCar
	ExampleGetRawRequestResponseVehicleTruck
	ExampleGetRawRequestResponseVehicleBike
)

func NewExampleGetRawRequestResponseVehicle(name string) ExampleGetRawRequestResponseVehicle {
	switch name {
	case "car":
		return ExampleGetRawRequestResponseVehicleCar
	case "truck":
		return ExampleGetRawRequestResponseVehicleTruck
	case "bike":
		return ExampleGetRawRequestResponseVehicleBike
	}

	return ExampleGetRawRequestResponseVehicle(0)
}

var ExampleGetRawRequestResponseVehicleString = map[ExampleGetRawRequestResponseVehicle]string{
	ExampleGetRawRequestResponseVehicleCar:   "car",
	ExampleGetRawRequestResponseVehicleTruck: "truck",
	ExampleGetRawRequestResponseVehicleBike:  "bike",
}

func (e ExampleGetRawRequestResponseVehicle) String() string {
	return ExampleGetRawRequestResponseVehicleString[e]
}

func (e *ExampleGetRawRequestResponseVehicle) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleGetRawRequestResponseVehicle(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleGetRawRequestResponseVehicle(s)

	return nil
}

func (e ExampleGetRawRequestResponseVehicle) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleGetRawRequestResponseVehicle) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleGetRawRequestResponseVehicle) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleGetRawRequestResponseVehicle.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleGetRawRequestResponseVehicle(s)

	return nil
}

// ExampleGetRawRequestResponseAndHeadersVehicle
// Op: getRawRequestResponseAndHeaders Param: vehicle
type ExampleGetRawRequestResponseAndHeadersVehicle int8

const (
	UnknownExampleGetRawRequestResponseAndHeadersVehicle ExampleGetRawRequestResponseAndHeadersVehicle = iota
	ExampleGetRawRequestResponseAndHeadersVehicleCar
	ExampleGetRawRequestResponseAndHeadersVehicleTruck
	ExampleGetRawRequestResponseAndHeadersVehicleBike
)

func NewExampleGetRawRequestResponseAndHeadersVehicle(name string) ExampleGetRawRequestResponseAndHeadersVehicle {
	switch name {
	case "car":
		return ExampleGetRawRequestResponseAndHeadersVehicleCar
	case "truck":
		return ExampleGetRawRequestResponseAndHeadersVehicleTruck
	case "bike":
		return ExampleGetRawRequestResponseAndHeadersVehicleBike
	}

	return ExampleGetRawRequestResponseAndHeadersVehicle(0)
}

var ExampleGetRawRequestResponseAndHeadersVehicleString = map[ExampleGetRawRequestResponseAndHeadersVehicle]string{
	ExampleGetRawRequestResponseAndHeadersVehicleCar:   "car",
	ExampleGetRawRequestResponseAndHeadersVehicleTruck: "truck",
	ExampleGetRawRequestResponseAndHeadersVehicleBike:  "bike",
}

func (e ExampleGetRawRequestResponseAndHeadersVehicle) String() string {
	return ExampleGetRawRequestResponseAndHeadersVehicleString[e]
}

func (e *ExampleGetRawRequestResponseAndHeadersVehicle) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleGetRawRequestResponseAndHeadersVehicle(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleGetRawRequestResponseAndHeadersVehicle(s)

	return nil
}

func (e ExampleGetRawRequestResponseAndHeadersVehicle) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleGetRawRequestResponseAndHeadersVehicle) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleGetRawRequestResponseAndHeadersVehicle) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleGetRawRequestResponseAndHeadersVehicle.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleGetRawRequestResponseAndHeadersVehicle(s)

	return nil
}

// ExampleGetRawResponseVehicle
// Op: getRawResponse Param: vehicle
type ExampleGetRawResponseVehicle int8

const (
	UnknownExampleGetRawResponseVehicle ExampleGetRawResponseVehicle = iota
	ExampleGetRawResponseVehicleCar
	ExampleGetRawResponseVehicleTruck
	ExampleGetRawResponseVehicleBike
)

func NewExampleGetRawResponseVehicle(name string) ExampleGetRawResponseVehicle {
	switch name {
	case "car":
		return ExampleGetRawResponseVehicleCar
	case "truck":
		return ExampleGetRawResponseVehicleTruck
	case "bike":
		return ExampleGetRawResponseVehicleBike
	}

	return ExampleGetRawResponseVehicle(0)
}

var ExampleGetRawResponseVehicleString = map[ExampleGetRawResponseVehicle]string{
	ExampleGetRawResponseVehicleCar:   "car",
	ExampleGetRawResponseVehicleTruck: "truck",
	ExampleGetRawResponseVehicleBike:  "bike",
}

func (e ExampleGetRawResponseVehicle) String() string {
	return ExampleGetRawResponseVehicleString[e]
}

func (e *ExampleGetRawResponseVehicle) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleGetRawResponseVehicle(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleGetRawResponseVehicle(s)

	return nil
}

func (e ExampleGetRawResponseVehicle) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleGetRawResponseVehicle) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleGetRawResponseVehicle) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleGetRawResponseVehicle.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleGetRawResponseVehicle(s)

	return nil
}

// ExampleGetTestVehicle
// Op: getTest Param: vehicle
type ExampleGetTestVehicle int8

const (
	UnknownExampleGetTestVehicle ExampleGetTestVehicle = iota
	ExampleGetTestVehicleCar
	ExampleGetTestVehicleTruck
	ExampleGetTestVehicleBike
)

func NewExampleGetTestVehicle(name string) ExampleGetTestVehicle {
	switch name {
	case "car":
		return ExampleGetTestVehicleCar
	case "truck":
		return ExampleGetTestVehicleTruck
	case "bike":
		return ExampleGetTestVehicleBike
	}

	return ExampleGetTestVehicle(0)
}

var ExampleGetTestVehicleString = map[ExampleGetTestVehicle]string{
	ExampleGetTestVehicleCar:   "car",
	ExampleGetTestVehicleTruck: "truck",
	ExampleGetTestVehicleBike:  "bike",
}

func (e ExampleGetTestVehicle) String() string {
	return ExampleGetTestVehicleString[e]
}

func (e *ExampleGetTestVehicle) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleGetTestVehicle(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleGetTestVehicle(s)

	return nil
}

func (e ExampleGetTestVehicle) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleGetTestVehicle) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleGetTestVehicle) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleGetTestVehicle.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleGetTestVehicle(s)

	return nil
}

// ExampleGetTestVehicleDefault
// Op: getTest Param: vehicleDefault
type ExampleGetTestVehicleDefault int8

const (
	UnknownExampleGetTestVehicleDefault ExampleGetTestVehicleDefault = iota
	ExampleGetTestVehicleDefaultCar
	ExampleGetTestVehicleDefaultTruck
	ExampleGetTestVehicleDefaultBike
)

func NewExampleGetTestVehicleDefault(name string) ExampleGetTestVehicleDefault {
	switch name {
	case "car":
		return ExampleGetTestVehicleDefaultCar
	case "truck":
		return ExampleGetTestVehicleDefaultTruck
	case "bike":
		return ExampleGetTestVehicleDefaultBike
	}

	return ExampleGetTestVehicleDefault(0)
}

var ExampleGetTestVehicleDefaultString = map[ExampleGetTestVehicleDefault]string{
	ExampleGetTestVehicleDefaultCar:   "car",
	ExampleGetTestVehicleDefaultTruck: "truck",
	ExampleGetTestVehicleDefaultBike:  "bike",
}

func (e ExampleGetTestVehicleDefault) String() string {
	return ExampleGetTestVehicleDefaultString[e]
}

func (e *ExampleGetTestVehicleDefault) UnmarshalJSON(input []byte) (err error) {
	var i int8

	err = json.Unmarshal(input, &i)
	if err == nil {
		*e = ExampleGetTestVehicleDefault(i)
		return nil
	}

	var s string

	err = json.Unmarshal(input, &s)
	if err != nil {
		return err
	}

	*e = NewExampleGetTestVehicleDefault(s)

	return nil
}

func (e ExampleGetTestVehicleDefault) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

func (e ExampleGetTestVehicleDefault) Value() (driver.Value, error) {
	return json.Marshal(e.String())
}

func (e *ExampleGetTestVehicleDefault) Scan(src any) error {
	s, ok := src.(string)
	if !ok {
		return fmt.Errorf("ExampleGetTestVehicleDefault.scan: scanned a %T, not []byte", src) //nolint
	}

	*e = NewExampleGetTestVehicleDefault(s)

	return nil
}
