// Code generated by foji, template: foji/openapi/client.go.tpl; DO NOT EDIT.

package example

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/bir/iken/httputil"
	"github.com/google/uuid"
)

type (
	ClientAuthenticator         = httputil.ClientAuthenticateFunc[*ExampleAuth]
	ClientTokenAuthenticator    = httputil.ClientTokenAuthenticatorFunc[*ExampleAuth]
	ClientBasicAuthenticator    = httputil.ClientBasicAuthenticatorFunc[*ExampleAuth]
	ClientCookieAuthenticator   = httputil.ClientCookieAuthenticatorFunc[*ExampleAuth]
	ClientWrappingAuthenticator = httputil.ClientWrappingAuthenticatorFunc[*ExampleAuth]
	ClientSecurityGroup         = httputil.ClientSecurityGroup[*ExampleAuth]
	ClientSecurityGroups        = httputil.ClientSecurityGroups[*ExampleAuth]
)

type Client struct {
	baseURL                     string
	httpClient                  *http.Client
	bearerAuth                  ClientAuthenticator
	customHeaderAuthAuth        ClientAuthenticator
	headerAuthAuth              ClientAuthenticator
	jwtAuth                     ClientAuthenticator
	rawAuth                     ClientAuthenticator
	getAuthComplexSecurity      ClientSecurityGroups
	getAuthSimpleMaybeSecurity  ClientSecurityGroups
	getAuthSimple2MaybeSecurity ClientSecurityGroups
	getAuthComplexMaybeSecurity ClientSecurityGroups
	getComplexSecuritySecurity  ClientSecurityGroups
}

func NewClient(baseURL string, httpClient *http.Client, bearerAuth ClientTokenAuthenticator, customHeaderAuthAuth ClientTokenAuthenticator, headerAuthAuth ClientTokenAuthenticator, jwtAuth ClientTokenAuthenticator, rawAuth ClientTokenAuthenticator) *Client {
	c := &Client{
		baseURL:              baseURL,
		httpClient:           httpClient,
		bearerAuth:           httputil.BearerClientAuth("Authorization", bearerAuth),
		customHeaderAuthAuth: httputil.HeaderClientAuth("X-CUSTOM-HEADER", customHeaderAuthAuth),
		headerAuthAuth:       httputil.HeaderClientAuth("Authorization", headerAuthAuth),
		jwtAuth:              httputil.QueryClientAuth("jwt", jwtAuth),
		rawAuth:              httputil.HeaderClientAuth("Authorization", rawAuth),
	}

	c.getAuthComplexSecurity = ClientSecurityGroups{
		ClientSecurityGroup{c.headerAuthAuth},
		ClientSecurityGroup{c.headerAuthAuth},
		ClientSecurityGroup{c.jwtAuth},
	}

	c.getAuthSimpleMaybeSecurity = ClientSecurityGroups{
		ClientSecurityGroup{c.headerAuthAuth},
		ClientSecurityGroup{},
	}

	c.getAuthSimple2MaybeSecurity = ClientSecurityGroups{
		ClientSecurityGroup{c.headerAuthAuth},
		ClientSecurityGroup{c.headerAuthAuth},
		ClientSecurityGroup{},
	}

	c.getAuthComplexMaybeSecurity = ClientSecurityGroups{
		ClientSecurityGroup{c.headerAuthAuth},
		ClientSecurityGroup{c.jwtAuth},
		ClientSecurityGroup{},
	}

	c.getComplexSecuritySecurity = ClientSecurityGroups{
		ClientSecurityGroup{c.rawAuth},
		ClientSecurityGroup{c.bearerAuth},
		ClientSecurityGroup{c.customHeaderAuthAuth},
	}

	return c
}

// GetExamples
func (c *Client) GetExamples(ctx context.Context) (*Examples, error) {
	u := c.baseURL + "/examples"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out Examples
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetAuthComplex
func (c *Client) GetAuthComplex(ctx context.Context, user *ExampleAuth) error {
	u := c.baseURL + "/examples/auth/complex"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.getAuthComplexSecurity.Auth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// GetAuthSimple
func (c *Client) GetAuthSimple(ctx context.Context, user *ExampleAuth) error {
	u := c.baseURL + "/examples/auth/simple"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.headerAuthAuth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// GetAuthSimpleMaybe
func (c *Client) GetAuthSimpleMaybe(ctx context.Context, user *ExampleAuth) error {
	u := c.baseURL + "/examples/auth/simple/maybe"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.getAuthSimpleMaybeSecurity.Auth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// GetAuthSimple2
func (c *Client) GetAuthSimple2(ctx context.Context, user *ExampleAuth) error {
	u := c.baseURL + "/examples/auth/simple2"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.headerAuthAuth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// GetAuthSimple2Maybe
func (c *Client) GetAuthSimple2Maybe(ctx context.Context, user *ExampleAuth) error {
	u := c.baseURL + "/examples/auth/simple2/maybe"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.getAuthSimple2MaybeSecurity.Auth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// GetAuthComplexMaybe
func (c *Client) GetAuthComplexMaybe(ctx context.Context, user *ExampleAuth) error {
	u := c.baseURL + "/examples/complexAuthMaybe"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient
	httpClient, err = c.getAuthComplexMaybeSecurity.Auth(req, httpClient, user)
	if err != nil {
		return err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// GetComplexSecurity
func (c *Client) GetComplexSecurity(ctx context.Context, user *ExampleAuth) ([]TestInt, error) {
	u := c.baseURL + "/examples/complexSecurity"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient
	httpClient, err = c.getComplexSecuritySecurity.Auth(req, httpClient, user)
	if err != nil {
		return nil, err
	}

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out []TestInt
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return out, nil
}

// AddForm
func (c *Client) AddForm(ctx context.Context, body AddFormRequest) (*FooBar, error) {
	u := c.baseURL + "/examples/form"

	form := url.Values{}
	form.Set("f01", strconv.FormatBool(body.F01))
	if body.F01Null != nil {
		form.Set("f01Null", strconv.FormatBool((*body.F01Null)))
	}
	form.Set("f01b", strconv.FormatBool(body.F01B))
	if body.F01BNull != nil {
		form.Set("f01bNull", strconv.FormatBool((*body.F01BNull)))
	}
	form.Set("f02", strconv.FormatInt(int64(body.F02), 10))
	if body.F02Null != nil {
		form.Set("f02Null", strconv.FormatInt(int64((*body.F02Null)), 10))
	}
	form.Set("f03", strconv.FormatInt(int64(body.F03), 10))
	if body.F03Null != nil {
		form.Set("f03Null", strconv.FormatInt(int64((*body.F03Null)), 10))
	}
	form.Set("f04", strconv.FormatInt(body.F04, 10))
	if body.F04Null != nil {
		form.Set("f04Null", strconv.FormatInt((*body.F04Null), 10))
	}
	form.Set("f05", body.F05.Format(time.RFC3339))
	if body.F05Null != nil {
		form.Set("f05Null", (*body.F05Null).Format(time.RFC3339))
	}
	form.Set("f06", body.F06.String())
	if body.F06Null != nil {
		form.Set("f06Null", (*body.F06Null).String())
	}
	form.Set("f07", body.F07)
	if body.F07Null != nil {
		form.Set("f07Null", (*body.F07Null))
	}
	form.Set("f08", body.F08.String())
	if body.F08Null != nil {
		form.Set("f08Null", (*body.F08Null).String())
	}
	form.Set("f09", body.F09.String())
	if body.F09Null != nil {
		form.Set("f09Null", (*body.F09Null).String())
	}
	for _, v := range body.F10 {
		form.Add("f10", v)
	}
	for _, v := range body.F11 {
		form.Add("f11", strconv.FormatInt(int64(v), 10))
	}
	for _, v := range body.F12 {
		form.Add("f12", v.String())
	}
	form.Set("f13", body.F13)
	if body.F13Null != nil {
		form.Set("f13Null", (*body.F13Null))
	}

	reqBody := strings.NewReader(form.Encode())
	contentType := "application/x-www-form-urlencoded"

	req, err := http.NewRequestWithContext(ctx, "POST", u, reqBody)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", contentType)

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out FooBar
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// AddMultipartForm
func (c *Client) AddMultipartForm(ctx context.Context, body AddMultipartFormRequest) (*FooBar, error) {
	u := c.baseURL + "/examples/form:multipart"

	var bodyBuf bytes.Buffer

	mw := multipart.NewWriter(&bodyBuf)
	if err := mw.WriteField("f1", strconv.FormatBool(body.F1)); err != nil {
		return nil, fmt.Errorf("multipart field f1: %w", err)
	}
	if err := mw.WriteField("f2", strconv.FormatInt(int64(body.F2), 10)); err != nil {
		return nil, fmt.Errorf("multipart field f2: %w", err)
	}
	if err := mw.WriteField("f3", strconv.FormatInt(int64(body.F3), 10)); err != nil {
		return nil, fmt.Errorf("multipart field f3: %w", err)
	}
	if err := mw.WriteField("f4", strconv.FormatInt(body.F4, 10)); err != nil {
		return nil, fmt.Errorf("multipart field f4: %w", err)
	}
	if err := mw.WriteField("f5", body.F5.Format(time.RFC3339)); err != nil {
		return nil, fmt.Errorf("multipart field f5: %w", err)
	}
	if err := mw.WriteField("f6", body.F6.String()); err != nil {
		return nil, fmt.Errorf("multipart field f6: %w", err)
	}
	if err := mw.WriteField("f7", body.F7); err != nil {
		return nil, fmt.Errorf("multipart field f7: %w", err)
	}
	{
		part, err := mw.CreateFormFile("file1", body.File1.Filename)
		if err != nil {
			return nil, fmt.Errorf("multipart file file1: %w", err)
		}

		if _, err := io.Copy(part, body.File1.File); err != nil {
			return nil, fmt.Errorf("multipart file file1: %w", err)
		}
	}
	if body.File2.File != nil {
		{
			part, err := mw.CreateFormFile("file2", body.File2.Filename)
			if err != nil {
				return nil, fmt.Errorf("multipart file file2: %w", err)
			}

			if _, err := io.Copy(part, body.File2.File); err != nil {
				return nil, fmt.Errorf("multipart file file2: %w", err)
			}
		}
	}

	if err := mw.Close(); err != nil {
		return nil, fmt.Errorf("multipart close: %w", err)
	}

	reqBody := &bodyBuf
	contentType := mw.FormDataContentType()

	req, err := http.NewRequestWithContext(ctx, "POST", u, reqBody)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", contentType)

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out FooBar
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// HeaderResponse
// Check header responses
func (c *Client) HeaderResponse(ctx context.Context) error {
	u := c.baseURL + "/examples/header"

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// AddInlinedAllOf
func (c *Client) AddInlinedAllOf(ctx context.Context, body AddInlinedAllOfRequest) (*FooBar, error) {
	u := c.baseURL + "/examples/inlinedAllOf"

	buf, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("marshal request body: %w", err)
	}

	reqBody := bytes.NewReader(buf)
	contentType := "application/json"

	req, err := http.NewRequestWithContext(ctx, "POST", u, reqBody)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", contentType)

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out FooBar
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// AddInlinedBody
func (c *Client) AddInlinedBody(ctx context.Context, body AddInlinedBodyRequest) (*FooBar, error) {
	u := c.baseURL + "/examples/inlinedBody"

	buf, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("marshal request body: %w", err)
	}

	reqBody := bytes.NewReader(buf)
	contentType := "application/json"

	req, err := http.NewRequestWithContext(ctx, "POST", u, reqBody)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", contentType)

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out FooBar
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetExampleParams
func (c *Client) GetExampleParams(ctx context.Context, k1 string, k2 uuid.UUID, k3 time.Time, k4 int32, k5 int64, enumTest GetExampleParamsEnumTest) (*Example, error) {
	u := c.baseURL + "/examples/key1/{k1}/key2/{k2}/key3/{k3}/key4/{key4}/key5/{key5}"
	queryParams := url.Values{}
	u = strings.Replace(u, "{k1}", url.PathEscape(k1), 1)
	u = strings.Replace(u, "{k2}", url.PathEscape(k2.String()), 1)
	u = strings.Replace(u, "{k3}", url.PathEscape(k3.Format(time.RFC3339)), 1)
	u = strings.Replace(u, "{k4}", url.PathEscape(strconv.FormatInt(int64(k4), 10)), 1)
	u = strings.Replace(u, "{k5}", url.PathEscape(strconv.FormatInt(k5, 10)), 1)
	queryParams.Set("enumTest", enumTest.String())

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out Example
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// NoResponse
func (c *Client) NoResponse(ctx context.Context, body Foo) error {
	u := c.baseURL + "/examples/noResponse"

	buf, err := json.Marshal(body)
	if err != nil {
		return fmt.Errorf("marshal request body: %w", err)
	}

	reqBody := bytes.NewReader(buf)
	contentType := "application/json"

	req, err := http.NewRequestWithContext(ctx, "POST", u, reqBody)
	if err != nil {
		return err
	}

	req.Header.Set("Content-Type", contentType)

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	return nil
}

// GetExampleOptional
func (c *Client) GetExampleOptional(ctx context.Context, k1 *string, k2 *uuid.UUID, k3 *time.Time, k4 *int32, k5 *int64, k5Default int64) (*Example, error) {
	u := c.baseURL + "/examples/optional"
	queryParams := url.Values{}
	if k1 != nil {
		queryParams.Set("k1", (*k1))
	}
	if k2 != nil {
		queryParams.Set("k2", (*k2).String())
	}
	if k3 != nil {
		queryParams.Set("k3", (*k3).Format(time.RFC3339))
	}
	if k4 != nil {
		queryParams.Set("k4", strconv.FormatInt(int64((*k4)), 10))
	}
	if k5 != nil {
		queryParams.Set("k5", strconv.FormatInt((*k5), 10))
	}
	queryParams.Set("k5Default", strconv.FormatInt(k5Default, 10))

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out Example
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetExampleQuery
func (c *Client) GetExampleQuery(ctx context.Context, k1 string, k2 uuid.UUID, k3 time.Time, k4 int32, k5 int64, k6 []string, k7 []uuid.UUID) (*Example, error) {
	u := c.baseURL + "/examples/query"
	queryParams := url.Values{}
	queryParams.Set("k1", k1)
	queryParams.Set("k2", k2.String())
	queryParams.Set("k3", k3.Format(time.RFC3339))
	queryParams.Set("k4", strconv.FormatInt(int64(k4), 10))
	queryParams.Set("k5", strconv.FormatInt(k5, 10))
	for _, v := range k6 {
		queryParams.Add("k6", v)
	}
	for _, v := range k7 {
		queryParams.Add("k7", v.String())
	}

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out Example
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetRawBody
func (c *Client) GetRawBody(ctx context.Context, body Foo) (*Example, error) {
	u := c.baseURL + "/examples/rawBody"

	buf, err := json.Marshal(body)
	if err != nil {
		return nil, fmt.Errorf("marshal request body: %w", err)
	}

	reqBody := bytes.NewReader(buf)
	contentType := "application/json"

	req, err := http.NewRequestWithContext(ctx, "GET", u, reqBody)
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", contentType)

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out Example
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetRawRequest
func (c *Client) GetRawRequest(ctx context.Context, vehicle GetRawRequestVehicle) (*Example, error) {
	u := c.baseURL + "/examples/rawRequest"
	queryParams := url.Values{}
	queryParams.Set("vehicle", vehicle.String())

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out Example
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetRawRequestResponse
func (c *Client) GetRawRequestResponse(ctx context.Context, vehicle GetRawRequestResponseVehicle) (*Example, error) {
	u := c.baseURL + "/examples/rawRequestResponse"
	queryParams := url.Values{}
	queryParams.Set("vehicle", vehicle.String())

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out Example
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetRawRequestResponseAndHeaders
func (c *Client) GetRawRequestResponseAndHeaders(ctx context.Context, vehicle GetRawRequestResponseAndHeadersVehicle) (*Example, error) {
	u := c.baseURL + "/examples/rawRequestResponseAndHeaders"
	queryParams := url.Values{}
	queryParams.Set("vehicle", vehicle.String())

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out Example
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetRawResponse
func (c *Client) GetRawResponse(ctx context.Context, vehicle GetRawResponseVehicle) (*Example, error) {
	u := c.baseURL + "/examples/rawResponse"
	queryParams := url.Values{}
	queryParams.Set("vehicle", vehicle.String())

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out Example
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}

// GetTest
func (c *Client) GetTest(ctx context.Context, vehicle GetTestVehicle, vehicleDefault GetTestVehicleDefault, playerID uuid.UUID, color ColorQuery, colorDefault ColorQueryDefault, season Season) (*Example, error) {
	u := c.baseURL + "/examples/test"
	queryParams := url.Values{}
	queryParams.Set("vehicle", vehicle.String())
	queryParams.Set("vehicleDefault", vehicleDefault.String())
	queryParams.Set("playerId", playerID.String())
	queryParams.Set("color", color.String())
	queryParams.Set("colorDefault", colorDefault.String())
	u = strings.Replace(u, "{season}", url.PathEscape(season.String()), 1)

	if len(queryParams) > 0 {
		u += "?" + queryParams.Encode()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", u, http.NoBody)
	if err != nil {
		return nil, err
	}

	httpClient := c.httpClient

	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		errBody, _ := io.ReadAll(resp.Body)

		return nil, httputil.UnexpectedResponseError{Resp: resp, URL: u, Body: errBody}
	}

	var out Example
	if err := httputil.GetJSONBody(resp.Body, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
